// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hvtctu4kvatdPG8VbHzipT8kcwZT+0Pj6xJVBs7XsvJ7NYoZUJkS8QxCXAAULY25apzEece9j72Us6V",
	"bDUAUl+0opydTW1t5V8i4qPRaHQ//XT7c5DIopQChdHB2eegZIoVaFDZ//XzShtUw/SamYx+SFEnipeG",
	"SxGcBRf9yzDHOeaQuIGgUMtKJQg8RWH4lKOCA80KhDnLKwSm4f3ovP9CQ+zXjngaw9//+je4uAh7f+69",
	"0DC8gEtWllzMQEiDh1HQCThtV5IQnUCwAoOzIKllCzqBwt8rrjANzoyqsBPoJMOCkcBmUdJgbRQXs+Dp",
	"6an+uHq+7ZOdb5+oYILNMIXJwh6BpCqVLFEZjnaxRCEzeGc4ifc5mEpVMBOcBSkzGNpfSVCWvhf5ohZ0",
	"Q7xOwNNtYUZf1N/BTuV9cdP7aoKJFFM+2978Z6bx9WmIIpEpprAcGsG1LKucGUxBinwBDxkKiLVhptIx",
	"cA34yBKTLyA+798OPw5iOLgZ/Ev4ZnAb9o573d5J7/AnYPkDW2jAojQLkALecW0AhVEctRv/bji6DWnw",
	"XkcRMsU7jc6YWZpyOgbLr9du6v8pnAZnwZ+6S9vveqvoerVeyRRHaGjJdX0Mkkzi8hbccaNm2xgKVkLK",
	"Fdqjk2ELCTHJvYi7sZGG5THQvpVhtGQHNBcJbl6r3z+GjGlaQVdJBlOOeQoHo354eRL2ese7VCInf8HE",
	"yl+2vt2b2q7pM0ylApNxXZt90AnwkRVlvvLSdPfo+ARPX73+IcQ//zgJj47Tk5Cdvnodnh6/fn10evTD",
	"aa/X2+eSnNL2vImRG9xMuytQazbD7SO9rQomQtqdTXIEPw7YRFYGTIaQVEqhMOD330PSqkz/+296jkpb",
	"CT+32VIKUyULK1/fehAgb4baWPMqMYn8/DhaDtClFBrduyMbkwU37iHCGzRd+4r2s5PGM6560d/IDzX3",
	"9GnTqDrBY8iwDGvf6AKHMaiEpsmNwXz2/3qiNcq8UixfsSfagYtZlTO1/DVYbqZZEmpUc55gWCo55ymq",
	"KE2KiMtuPZrk9obilHPjlLet7HXlwkSmiwgumUky1JBIYZTMwzJnAl9oYImpWA6yMhNZiRRSrksaCjpj",
	"JVqVx5/HAV3PODiDz1EUPT3F9j465HiBwQwFKp7AzWB022gKUMwxlyXWLvtwO47Qovu+DRq6eXV2/qcW",
	"R+AnkXG0RLzBdXh0cgwlm3FhPRM8KFaWqLYlFPho7ko2wzsj77HNsMmdd9lE02urw4CNDyZDhcAUklOb",
	"Vor+T/Zc5WbN3586zWy9JT+UtuQGi32dCE31azGl2GJLafW6O/R2iYalzFhYsa6PnE0w3xlxts6xrq9L",
	"VAQtHrjJ4IDMR2GZs8SijUPrGkymECH21v8yBvkgUOmMl+B2t6NG13VApVjk9Nm/GZzfDpoIunU6B6e+",
	"4EtrNESDI4swMAUjl2GQ/FThFRTRqLjl+jZ0bnfeofA6Bm8Jd8mVkko/GzMP4kxqc0frxh2INf93jA/t",
	"o9WI0LjFbcNuprXeGa2z8oELgzPvgnYdQW8fgH4GB6Mq5R6bi8CNpiO4khB7t3Rn3VIMkyq5R3NWn/ut",
	"1OTz+24QXNMg7XGqW8t/sdOB5FWC5eSitLQDah/lXgupkoCMjjb29RgkkcpFnpTgJQnhEQkTKeE9Mlz7",
	"4g9IzZcnQFYB//kfp9ER/GIHemja4vQepLp3QHyP1/yrHex0u2lUfqEdZnXtQ8lbXuc8a5JQ2PmSHHT2",
	"9WU2xbCr7BBi5J38BtL30Y5mhaQ9PuUJcFFWBur/Ls2FNc/y4J+rCSqBBjX4DTbutkXlxYo/20Ppjfvz",
	"KPtrkLSFb3UIv8tqxe8xe0PLO8DUigoKLqQCPxIOMJpFMA6OopPeODiM4FYxoV3isnwT5M2YcFYdK8yR",
	"abzjBZthDHPOgEHGVOqSIOubM5mnqMBY/7jmaY9fHUIlctQa4vVDR2QW0cbqco5K8RQ1cBOBx4QTltzT",
	"CSbM8IJg3Ro+3IR/DeYjHAh8C/stsTwp4YuOudZxfdGdpa1sXeMuG29g/hZt8ELDtMpzSJiQgicshx9C",
	"l+HW5uuwJ8xlwiaEEBcOMf3YO/RJlYP0r/w0XU00GuBOUQ46loAiYyLBgpxSKpMXmsImOLmaPNneoNWS",
	"qAo6/vXN+zc3g9FoePUm6AQueQ06wcXgzc35xeAi6AQfrs4/ng/fnf/8jj78cj58Z3++GLwb3LpZ9p+D",
	"ixX1LONIixfb8kKJrERL5LuqigkqkFNwfg6cv34uIjdp6W/3uPgU2UBIJy244AUd9qizFc06QVJW2zsP",
	"hUt+LLhxlrdm9D/4i1kJvRQTpvzRcSYWxGBR0rv7qQYrAueoIEXF56ib5+eCis+KuF4BEitCFlhItfiH",
	"5Ixg4DzCyfGbn8dBK87URqrWJPNr1j9+1Xtmg40H52677SkNCOm0ZO+/9OHH01c/WCYh54xgNo1c+oaD",
	"ayUnORZwgYbxXNuI8fb29hrOr4f60DoF5/suZKKf3+EMdi4UdIJKUVKXGVPqs26XvIRRLLlHFXE000iq",
	"WTeVSTczRd5V04QW9eFgxd5Tu/gXcSg+EiRxIbCJj0Y67kImLsFPsO1GudCGnMH2Hh9uhqBwinbqkgpp",
	"1neaXVu9IQIqxcNmbrCT69g4GGnQOzmKKquLcmFOjlut3nCTt5xglEllIFvXla6KgqlFm1A1xN2lB8/g",
	"LqyLzNBrgWZG8EGjSzgu+pdQKknWGnrQmGMKjTEkReg/RzNusmpC2UvpDEp3X9p8QpcswQ4UlF83myVS",
	"L7TB4oWGxtYLPvNg2QJMlhShB0BbNIGFpPd/1lYoxkXLkMNVl7+nwFzMWc7TkKlZRUEl6Ow7U0gTTmUl",
	"0v2nsNyyhiE+cm30/vNKVAXXFMDDFAXHr9iyEqwyGd17QvBo/4k1jvqqreaM52Sp5Pj2fFCd4DGkOwvn",
	"TFnbocsbXn08fze8OL958+FycHUbdIKr97e/vP9wRTH5/N3N4Pzi3wb/OhzdjoJOcD24uRyORsP3VxeD",
	"q2EdzT/cvh1c3Q7757f2l+HV7eDm6vzdRqj/tOm3rXD1q2xz32+R5W3sq/u9fv+ai1mORoqm2hDs6x9/",
	"zVBAJTK73qIDKdeGi1nFdeafaMIqCgeWqQFvwDDXkY21Y1EJhSzJrMeg+D2RJoOCLWCCYBQhK15UuWEC",
	"ZaXzxWEE547WechQjOuNo7FYg5nvhxd9WNvyJx/bq3zK89wiMv8iYUWEfejUdj673yBJS2jLqT38ij6X",
	"wjmZv46o3nF9q27EaYOCYq0ZMovNrb/CJzc0PX1eqaqtHWgnU9qc9tkntgcLXhPgm+lqIkWqfQWD9F1f",
	"aeOHtWHKeZJG3JPXvd6zm67EumczvdHmJpOK5ykss5alZnpRLzoKU5x/NQHun3Zzxb74uNzEK+WryXF/",
	"H6uEuPup5sOtJ2gqmUuCvLnIffhxP5hOtU1WbGUbE0pHU1kw3qLu96UHuyXT2mRKVrNsO9NAQxlJ9DJu",
	"hdNlled3GhPVRufttcHKCnEEvypuMCT0/QxLvJJh79iwTr0b9i2uay2hS0rSLS7AePLAwpCNrL89k9DZ",
	"3T0u/sFj0+yymuQ8oUXalVunVXdtxeObBtAZx/lZN1wTR/XUZzPIesAedO6qGNux8MlC8Kl0ya0wLLGW",
	"4Iv5hCOvHVjYyig8eEhksYopuq3mv02t08pbXslkzFjuhwClj5PvSxQwIotAPhNwPoR+LqsUDkgfh2NB",
	"ZyMX6lj6i/5lx61H5mL50BLFKONTUytXWxD68VJb/shpdSzaAuDs5rpP2VQ0FmPx8uUlz1EbKRBOQCey",
	"xLOXLxtepH/z4QIOHBPUrXmf7gXmaPDQsbAPY5HilAtMI/h46WaQ+9K27sLS1BJfwIBuS0HRbFeiAq51",
	"hfCnI5JVV7MZWo45xZzPUS2Wg7UV9hoVrIj7Qvs2jk7DXYeeQz64zphGODp0ObNN/BOW53osPK1F2nLn",
	"cHwX1zC6fqFB4YzT0TEFFGkpuTBrpFf3gy3SjgWdjlRqBxquMF84FmFDFk8DUYrvdnU0hAUhY+E3juA8",
	"z2EqKwXkKe2DdwrUhuc5eA2DrWeR+zi/HroUiCVmLGxejgYFamcHTCx8W0BXSBFuqodUgcrq9LYpkZkH",
	"Cc6RNyfXrrwoBXZggg7beYkbRWmaOBZcpFiiIMjQWL521mtTLDHnSgpriGyGXqmxN94YmBmL+HO971OX",
	"lbw7P2J5mbGjuvyqY3u2eF58Yfy80K7Lh4bT7m5Hd7gwyTC51+D0v3Ldy2zOwOrSblrs0kAyuKNezfwt",
	"jfFoLMiDHUbws1xVICgsKVu2cIUVBD9TVLnNcwm2WnLfS+Zgbc4TFBpX3NV5yZIM4TjqbXmrh4eHiNnP",
	"lvnwc3X33bA/uBoNwuOoF2WmyFeyeRuhoUY1dagmg1oBHGfBUdSLejRNlihYyYOz4CTqRacenNhA3n5L",
	"9GXWFnlv0FSKzLou+2IKueWRp0svJh9ETeE5OzuY8txd0GRB72VZl/Q9UuFk8U9pUmwVKa0FLGu8R73D",
	"CK7o7Y1F6XuJNMTLFqOYHAE9HBRGLTbbgezdNG9zmAZnAbmD/rK7YLWZ7bft8Mt+r3C13u3yFesxGJQK",
	"51xWumHUbHVsvfAdN61pv1domRZvHyu18V3NaJ2twiZ75EVVgGho3ro0biQoe1nWSdP6z+1dsEcnoi1X",
	"rm6f4pRVuQnOXvVayKbC7R2cHRE838UQP32ydXirFWtbx71eHdbRsdasLHNfqur+RTsQvxRkj7qPbVKw",
	"oGFdQ+82rJPew2nvaMf2nnH4/18nhuNdWwT4sEGR2P1Pvt3+1w27A57deeoEr3ZewB8swdBzPS7WKkcM",
	"OimOv50UO9iEJbFk2z09DeptZ6X5yLCZzcgaj/GJMhX5fPMQOUqBDxbLhROW3GO6DfuiTbgxFnX3kEWa",
	"fCUGN21BMU9jYLS+fc3QeC444EaPBeEVW9B1VcuGBjh02MJ2M4HnOimQWYxlEXzclMvYWLT3JLmepqYh",
	"CYYpFqWkOyT/S6KdASP3oxZj0chuY6eVW/koYlHFoyOgam280GtddzgWitmeH5Mx8u2eVl7LpE573YuL",
	"8KjX7uPdVfSbbrGdTr5vYVXItOYzimIt/ckd0GhWGmtJ1evNtWtZHinoxmc9VrVrl92031Rk+a6k+4yf",
	"5l/XuPzJDUZtfpbp4o92t+u9c0/rqR2J9rTl8o/+aBnaXnmd9bje6hQOpOoAn/r34ghyZ3OYdoCbDWtr",
	"AMfStA4j57K/ocO8JH8tZk5o27dR67Z+orbiGX2PZd9j2b6xrM6ZVxq2W8LZU+eZjKDmB7+UGJBLz9Zq",
	"FZ5Y36RUCB3XqWOdwynf4K5wmmNio4JCljsGynIeiRSCvsy5WdhItqwbjF3ZgJsF+VvK2PQy7HhZmIZ4",
	"K89sssO///VvTTb/QtfH4BRkHc3agVkuJywnMVzbZktGORYrKSW4jLIlKr3BJvF4uywv/A9h5Lc1ubtl",
	"Sb4wYRNqqDmINIJbStLqP82w3qbTtNCsVKLH9q88OsBFal2ChocMfbi2DRu81uPCZ/PL2hN9ttQIXb+z",
	"nuNez2l01A97veM6R2+U+L/itfv+MHsUfCwxoThTMsETChXrj85HoyZF9+ruk7pXXqC/n13v73Pz50tP",
	"7vXRRbW0Stnf9fKd02PwObsGLSk/dsgFWHIv5EOO6cwRmnQNrtWdbiqV6Bo0S2lprbVmU9v7Zjve8wWk",
	"XLOyRKbGwiIf18nkQiecQ3wlzS+yEmnsMmW790Edit050kPgeiyMD9okaZUkqDUcxMe90/iwA4Vt4bVR",
	"sY2cGwsjc1RsrSHDNpJDwrTvt6slO7Z4kbCrPSqNHYuGKrQd51OpsKH5nP7i095p3PaUnc6fBZhtlrcc",
	"0l3/k7mWVPm0Jbvw1+C1RyinATeuif7wOzb4jg32xQaeRP8CNuh8OfK353CVjtZJOq6hpu/SsVj+LSAt",
	"Ubiykg/Ye/1R4O7w+sc/yN63TGRcH8d32spLcPrtJKhvgIKg68T67lD2dChvsGG3GgPeL99Y4vE/NtWY",
	"F98yyxiLeGcaFTe449lUYyz2yDVg31Tj4+X3LOP/bJbx8fIrEgyaabdpLXG11RWbimXXBkO/5HOQ1FX0",
	"rJ9YlsGXJGZ/WYb5vMtI2ubW9vXp6b8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
