// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HzpbuPIdv+rHPD/B9ruSJS8dM+MB/mgtjVuAS3b8ZYEo4ZZIo/EuiarOFVFuXUbBvIQAfIIeYR8T94k",
	"TxKcqiK1kF7m3kzjIuhP45bIWs7yO7+zaL4GscwLKVAYHRx9DQqmWI4Glf3X7XiUXDCT0t8J6ljxwnAp",
	"gqPg5HjczXCBGdyOQaGWpYoReILC8BlHBTua5QgLlpUITMP51eD4jYboWOZFaXAktGEixpAnEfz3v/wr",
	"nJx09/b7bzSMTmDMioKLOQhpcDcMOgGnHQs6RycQLMfgKFjkoyToBAp/K7nCJDgyqsROoOMUc0bHNcuC",
	"ntNGcTEPHh8fqy/txYZKSdW81eUvx/DT4bsfgISScSYMID1JNyyk0Ag7F0pOM8zhBA3jmYaZVPDx+voC",
	"BhcjvRt0AvxiUAmWnchYP73DETy7UNAJSpUFR0FqTKGPer2EGWYUi+9RhRzNLJRq3ktk3EtNnvXULKZF",
	"g8dOUChZoDIc/ea0ePMYH8ucia5ClrBphoBfiowJRl+CLjDmMx6DkWBSrkHGcakUihiDzrZYSTdOk809",
	"bi5HoHCG9lV7Pbtcvb6T7MbqM6lyZoKjoFS8W7/btq02zJQt8rUSdF9CLJONRbkwB/urxbgwOEdFqxlu",
	"spYbXKVSGUg3ZaXLPGdq2XYo98HzcvAusiQDNyl6KdCbIdxo1PbDk+MxFEr+CWPTjaUwSmYZJlAbQ5x3",
	"/dfhnJu0nIZc9gpnULr3FshJdMFi7EDOTJzWm8VSL7XB/I2G2tZzPldO9TsaEVicd+Os1AZVV6Na8Bhp",
	"swVPUAETCdz/qO2hGBctj1iHRVHmwdGvwSsPzMWCZTzpMjUvcxQm6Lz2TSFNdyZLkbz+FZaRKpdd/MK1",
	"0a9/r0CVc625FN0EBcffsWUpWGlS0nvMzO95kUyUsOR3bbVgPCNLDT6/2qE6wZcu6ay7YMraDilvdHY7",
	"+DQ6GVye3oyHZ9dBJzg7v/7l/ObsJOgEg0+Xw8HJPw//aXR1fRV0govh5Xh0dTU6PzsZno2G9MjN2eDm",
	"+uPw7Hp0PLi2n4zOroeXZ4NP7svbwejT4MOnYfCZwHmF5L+6w1Ve+bk+rJzSrcnRPiLL2qKS+7zyf83F",
	"PEMjRR2ggtfi4z+mKKAUqV1v2YGEa8PFvOQ69S4as5LCgZH3KMAbMCx0aCPdRJRCIYtTixgU36bSpJCz",
	"JUwRKFSB5nmZGSZQljpb7oYwmGoUBh5SFJNq43AibERheUH4FJyPTo5hY8uf7X4wK7MZzzJyHvAeCWtH",
	"sJGSJeciW1aRsgFeRWucP2ZCCh6zDOh7kDN7+TV5rg7nzvyarZ4E73X1rcOIkwYFxUoyZBbbW/8OTL6s",
	"GAt9vUZbNi4kNYsb+BYmcU4eV9/2SRd7UQxlYXjeFnYwliKx9ksnTLFWaY3D2jDlkKQ+7sH7fv/JTddi",
	"3QKVtvs0t93aZFryLIHq+XXJ9MN+uNdNcPHyNdtdu1axZ3WrTbxQGl5PEMWw6NamZ8mqIXzUKxuh94qs",
	"VCyrrYJ2qZGg5onkzBlT62Zb7fcKrdOtyO9uxxf+gY+8ItAb+FKxo7unzLCiBUYCE86Xo4ocXy8LjCBm",
	"hmVyDiiMWoaWHGNCz1eUmghVuLFRFMLbt5de6m/frgj2fgeEhIQrjA1Ei7goo16UYy7VMoIZy7Ipi+/B",
	"RcZwQ+O0esJU0j3s7r1v9TPMi4wZvOPJC/ckg7YXvR1D9daT96oeiMK2TR+4SORDC5Kc2z8samltUiXL",
	"edqUmb7zC0Swo5ACXwIpKoQCFQyGF929Q0pJplJmyERXsJyIlCo9ptNFri7eaJAPAlJO0GszDBKyAbax",
	"t5xVe884ZollaLshnOCMlZnRdLZoxjKNUU/m3BhM1i7sD9B0pjWZd7ZsrS1s3o4HcYy6xU61Tu+Kcprx",
	"+O4el3+hPDcXadPYY+uhTri+bx4pZgWLuWk5zAVTGhOrJGvVB7ATnX6IetEp/xCBUUgki5LOU/7BG3u2",
	"7EB0Tc9c0zP/9W97/f3DDkRj+mhsP/oP+ggUkUlMoCw6EDONXS40Cs0NX5C+huE8hEmw1++ffpgEHZgE",
	"+9cfJkGrcbpMdfvwwy+MjgNSILGKexjfXF0TK3DmF02lNBHsXA7/oXs7Pr4cDq6H3f5BvwObn7zv71ob",
	"5AZyVuiGLmiZO1o/CmG4QLUEaVJUdkt6iHaLgGtrqoVCAjxMQAowigmd+YTg6rg7Puz2+/tutyeyeFJg",
	"BCmj1ew9nJG3G8C6AVsRdVaqbjfa0xK1Ob9qmkg7qD6FkDmbY+iCx53CWbR+u02wUylm3Z+CV8Wy9iOP",
	"Laa2+Bn/c8uJR8KRCOdiUmRL2HF4vbsGNCBwgarWj+WhXK9HDif1ykh/PG23zK1b2CM9dQvDEmZY8x4Z",
	"m2Jm/2JJwt3BL1p0s+YOW0pCNccEHrhJYYdsUGGRsRgTmC537YVNqhAh8oH3bUQoi0qnvAC3eyUWlj2w",
	"pQaNRm/7zbv+7poAVldrd82tosjt2NpyW2jKvWBC60avtPN2Gb9AIIiN0H//v8JZcBT8v96qXNfz9axe",
	"GxPZPoFdp/0EVwXGT7LBLr3QrWs2XBSlqUs4DiRmUgGDBVemZBnkLE65QNi59R+M/QdzFKh47GOk1cvm",
	"VVkdm567bB3DHjvBnIDhTr7inQpCHjtBXrvm8694F7ZvrNzgpXf8k64QZ/Vxl1aaff7dLf0RR5aKzfHl",
	"N6/8g0Tu46J8+YXb44ubJg74VdbEunb1xn2esKUnMruT4zFRnzLLIK4zyh+7rjx8O64y9oWM2ZR4eQWA",
	"ew4AGWgsmGIG1x+ZKZnDsStVvdHwg19OCvwZEmkjWyzFjLDSIcqDXC9OXVye346uRudno7PToBNc3pz5",
	"v66uzy8ubMHil8Hok/3jZPhpeL32rfvzYnBztfp6eLImlBXurfTTcG4Kxi5NMJi/wkQsUVpxKKYUWzb0",
	"6BZtV49VfJNpyVKYPzwq3WiEaNOIQkKlrdQF6J/I1slDnbxu3dSdu/WmDns89DSvNmjAVd3CyJlgcxuG",
	"7OmbMBVbfnlXpe51+p8wg1376StS/6pJcMeLO5YkygPfFlWMU4mr1onzkbDl1QjQs8odzAuzBLeRrSVB",
	"Ke4FJSikMhcdT4fXRCl3Q7iQRZlZtuxKIDHLLDWFUzS21ouWOn7i2rj8swqwn0ZXfo3X3LYtJbx6dXto",
	"59ne0Mubi79Y1C2v/q2Lur2KV5e7bBGvbsXcjjdo7yLXvb39Azx89/6HLv7407S7t58cdNnhu/fdw/33",
	"7/cO93447Pf7ryrxeVLBsux8Fhz9+mIMo+cfP3caB/+NglF3DX3e7R65hMUXS31Xya5ECU2pXfJH8HRs",
	"fRWUWwWmMlnCTnRxfnUNvUWuozfapfkHB91Vx2/96Q48pDxOaV23DVlttAkv0Qo8SAy7IZxZSCxWGhfA",
	"SM89q926l0hm4rs73SJjAn0pgcUWmh64siliwUycgjY8y0CjSLTD4ujrxEp5EhzB1zAMHx8JO+213cm1",
	"798pzBkXTiD2TSsGV4bgxtqdJc/hZmn2Jc5hn6vfuMtRax/knmXV/jlgU1kaV0m3/T+zKvu+onCa/LUQ",
	"vBVKbAHFH+B3lx7Jb74u8seN4uMirwqPvs64yF9ZY1zk9nibRkaW0xLHrPHuQ8Hm3LdvHxRlK6oZtwR+",
	"MXcFm+OdbSC0YCDhWY+5NkSFct7DUCEwhZTfz0plKwkKta1cbcDU4UbCtdKYf/j1XGczgL/Eearlm1zg",
	"0UaAmXQ8RxgWWzH6KYKT4zFcuGZao+Pum2uxzNd7br1W1TXzW1q5UbU3KTNg2YzyTAnhvEABV3KBCvlc",
	"wGAEx5ksE9ihWLQ7EUXGDBm4S5VPjscdt57mUlDgofevUj4z4Ju22kaT27GGBWc+ok1EW4NofnlxDIOL",
	"UTgRE/H27ZhnqI0UCIegY1ng0du3xM2PL29OYMdBaa9Csd4JZmhw15WQHiDBGReYhBPhCbl7jWtgSWIh",
	"MMECBYU+QqAlrHY7gJ2pYiJOMalpfrYkdJwIjehqfO8rbEswtnfXkMk5xVVUa2sdvtF+lKQzEdEGuEaw",
	"c5EyjbC362DQAh+FYV3FCRKcu5cthBF4Xl2Q9BTOOV0KE0CRFJILY9G7lsaNRSTrIr6SRjFe0T0oS2mc",
	"xSM95VxuW8eibcOu2jiEQZbBTJZqIsiRrX9rt4cNBl7mrmRNQX1wMXLjAiw2boQFDQrUziSYWE6EK4f2",
	"hBTdbfGQKFBZY7iuHd48SHBNj/rm2tW3pcAOTNH1Qf2RoRKUphcnYk3rtRdoZ8l2HEEsuJLCGiWboxdq",
	"5A05AmYmIvpa7fvYYwXvLfZYVqRsr1eZe2QvFy3yF56neO+SSZHY3d2O7nLdOMX4XgPJf0Pdq8kHA+tL",
	"u9ciNzJxctLt7/UrC11Z495EUITeDeGDXBcgKCykctHPMopSJKgyOxNyPjo5thUdfzLXAs54jELjGnQN",
	"ChanCPthv4FcDw8PIbNf2ykh/67ufRodD8+uht39sB+mJs/WJl9sNwuqDmBViiCDWmvOHQV7YT/s02uy",
	"QMEKHhwFB2E/PPSNPAvr7VqqOmdHX4M5mjaGakrlSUq60cX3LedtMCWaXhlKpTHnIh1QOMswNrZZgyxz",
	"aahFu1gKQd8suFlaQ1h11Ceuoc7NMoRLqx+9UpA/C9MQNayqtgWLWDVqVNcgCPSjCB2YZ3LKMjqGq5q2",
	"2M9ErBkQOPuxNlBjwCgJjoJTNB5p9cdV490xS6uH/X6/Cnro0ntWFJkv2vX+pF0LeDUw91w4/li1PRtx",
	"zrfsrfvUkJOEcJ1ilUZFjms61CCJrs1oTUQsE+xQeLCzMZoIh6UXvrrAKzkuve+upjLoawuEpH5nPfv9",
	"vpPo1XG339+vPLIW4mMnePesWPwczd/9PvG4acIW6Yx8AumCgvLDXjsYzkN3FfxSYEwpQsEEj3dDy2yq",
	"CbOjoIqltUN6cR+TuIlnsblloF4/dpCmYZ8v+hyr+CMmkFGGImeWP8gH4QohFbrvzHjmYNF+iBNRled9",
	"1aQ7Xf59EueNWv1aRux44h6lxEMLti7ZRZeAR20pdy9qq3lMRCNBbnETis63YzdpsJps/bXZ32S/lbjO",
	"o92UjS0xMso3F1yWus7dbAttk1BH9aTqbyXa+UCP1Guc+7kB1U6zj/WF52UOosynqEgpFeU2EpzF2x4o",
	"rf/U3jn74o5ouzzr2yeu8xwcveu3jEjmbu/gaK/f7wQ5F/5fLTW5z38g7rTkQC1e9snb7FZNz2anh/29",
	"b+fuN1tzfnb/g2+3/0U9ogh+RPFvAvDcKfa/3SmeGYlbTUduIq21oYYBrRCWMOTzYycoZFse7vIHQlKB",
	"D5ZudKcsvsdke8kQtlg3MXJX4akq5zU7rqtKEU8ioh4MrHdDjWSww42e2JKj7a6tlRdnHNWuo/2u3uMn",
	"dokTufIRBUUCUZcurUr6G8WyVVnt6fIXhd/1abqdRkmtA75y14FpafzWtCg3rpg1Ea4ctZ2S2KTIlcOy",
	"ZV1Q0y47Q1sh+9kVTifCzTc0anO+zqXBFzYsottEvLooCUnzvKBjlCJnSqcssyBLx/szKunq1FUt0Eoi",
	"ZSLJUAGfC6lQhxMxSjAvJFk3HY90dgSMcFotVzp1AiR9qjXCaweuuJhPxO34jd4oiCEo5vkQE8QZPIXY",
	"7HP/QOF0YPvgThvZAjXsSLWqFejduqZjR08c/INA8yDVPTBjWJzmPgebCNewux1XFlANd7jHyYpiKWIs",
	"zPZRfur3/vPfD8N3rdHY+YktOz8bjo9tKtplWvM5cZCWH5h0QKNZax2QE7S3DzbPt0+iurKX6sp6qqma",
	"9zo4gJ1JwMA1eaA+PeSlNpbApmxBGfsSqvrTyh21n7GxqrKV9tVXk2A1hfdu9+etaZ69fq//vu/T+pzd",
	"I3ADJHSVgCqF4TlW+5GKOoBiJpWblqjt2KYvfm7nsN8HPvM237Odit0NS7JGbH2jkl11nwhmGZt3/PTp",
	"hkPWoxYlYTdqe0qbTTt+mBCFs7NvpZHdCpKAJ/opfuLqrk9yos+uzIfafJDJ8g+iFS6CbP6S6LFBavb+",
	"0N03zf927A0wIR/ukCZdDHA/XXB4gUnHAtQmWqyI9jo2OCbyDXnAmGiImNtjdyCv/mWBf/VvtnKits5w",
	"nTiunrcTc+uTch2QyqVSBVMabYvBPhRVQ2UNBHhfC+Q7NfxODVuoobWp7QC5UXQnQE5AlnX0Oxu65sd2",
	"/u7ryts0sEEs2/L2P6Rktsi/ZbVsIqJny4GRZ53PlMwm4hU1M3htyex2/L1a9n+2WnY7/usKZb2vi3yU",
	"PDpPI820zLHZz3XTo8kLfDVNg5ZSVNQUWHwv5EOGydx1/Ej+jrCRimrKVEjb7HGqvB3bAaoq8Um4ZkWB",
	"TNU1Lzdw5vqtMIDoTJpfZCmIvFF+YzfeqeiCu0yyC1xPxNp4vC7tJCXsRPv9w2iX4ixJ3EbqtnbVRBiZ",
	"oWIbP+e1SYUdlYets+33e5u5JW1ft89sT3kmFdatLye+6LB/GLV5rxN9W+7QZmyrR3r1j9hbSlWHTRXf",
	"bk2GeenZbKqSqOPVu99ZxHcW8doCk+8rv0wFOi9H+0aVoNQUFOKsTBzpbiuiT0TUPjoYpxKT+ncy6wCy",
	"NcP2VEj9X/XI/rfMsxqubv9XDN/d2p3g8NudYFsTFBHd7/q/A8wrAeYUGwXs2qAb6Qa9ae/X2gxrmwWo",
	"pwx61mv9ei8FT9cXtDdYjbCsyj90mmbja4Mlt71WEezPj/8TAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
