// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rbttItu6rLPAcIFZGoiTbSXe7cX44tjsRTmT7WI7nbLQCs0QuSTUmq9hVRTmawMA8xAD7EeYR9v/Z",
	"bzJPslEX3iRKltPpTM/AfxqxyLqtWrVu31fsz17Ik5QzZEp6R5+9lAiSoEJh/jqJM6lQDKJLoub6hwhl",
	"KGiqKGfekXd6MuzEuMAYQvsiCJQ8EyECjZApOqUoYE+SBGFB4gyBSLgYHZ+8kBC4vn0aBfCPv/wVTk87",
	"ve97LyQMTmFI0pSyGTCusOV7bY/q4VI9ibbHSILekRfmc/PansBfMiow8o6UyLDtyXCOCdETVstUvyyV",
	"oGzmPTy0vZvh48u5GT5pJTxJM4UDJhVhIVZX1N9/wooWyRMX85A/rG7W+rqO17cnIYzMMILJ0qxCTygV",
	"PEWhKJrOQoFE4a2iemafvSkXCVHekRcRhR3zq54oiS5YvMwnujK9tkej9cmMHlWGva2a8Oigd9kEQ86m",
	"dLY++Bsi8fVhB1nII4ygfNWHS55mMVEYAWfxEu7nyCCQiqhMBkAl4CcSqngJwfHJ9eDmLIC9q7P/13l7",
	"dt3p7fe6vYNe60cg8T1ZSsAkVUvgDN5TqQCZEhSlff/9YHTd0S/vtBTGI7yVaE8miSKql0Hiy9pO/W+B",
	"U+/I+1/d8iB3nVZ0nVjPeYQjVLrLujzOwjnHchfscv1i2AASkkJEBZqla51mHAI972XQDRRXJA4gNOpP",
	"dJdtkJSFuLqtbvwA5kTqHmQWzmFKMY5gb3TSGR50er39bSLhkz9haOafNp7cq1yv9WOYcgFqTmWu9l7b",
	"w08kSeOK2ZDd/v4BHr56/V0Hv/9h0unvRwcdcvjqdedw//Xr/mH/u8Ner7fLJskUQ7M/cXwx9Y5+3mlH",
	"RrrRw8f22jp+yVCqjlFBfQ76/YPWkdVIK68g5EwJHnfSmDAMIHVqK7W+nZhD+yMwXKCAVKBEpvSDt6i6",
	"Whl9uHLGBVIUcJEiO74cwIGvT1twL6hCvdbgD0FuhALYE5VJtdqQUCG4XnxxPHTbXEyrTWXKmUTbFsiE",
	"L9Co0YSrOcyQoSDKGIKUU6a3BfYCnlBljlDQAqRqjgLuybINkgNzf0+5CFECAZlmgvIsP3PWrnAGao7A",
	"9asvJEgaoQ/HseSAzLSMgCjzypywKEYB1uqbE3pydXZ8fdbpvbZntJCJ3X+932bRT99x20zveV2lii5v",
	"E5SSzHBdvd9lCWEd3YxMYgT3nhZnZtcRZkLorXZz20FrszT69fZ9gUKaGX5usisRTAVPzPysYoLTJGNq",
	"Ugx91z7wyxesvliN14qilcEa5UKJd7QZFZdfetSftU8q9tAd3o+rdqbtfeoQTDu5u7SBkVIomNR9FDbk",
	"s/vXg+4jjTNB4oqJ0f1TNstiIspfvXIwScKORLGgIXZSwRc0QuFHYeJT3s3f1tN3GqTX3uDczy47/YN9",
	"SMmMMmOE4V6QNEWx7tQZflK3KZnhreJ32LRv+hR1ycTYjdzjGVeozxICEajt9zQT5hgKlFmsaq7t0B6b",
	"NVVxr+oh9ene1XPppq4vIgRZrm1n3u/HBl/h+hiiIhFRJoKqyyMmE4y3Ote1ddTlNUSho6h7quawx7gC",
	"gWlMQhNYtYzmq7lAhMDt6ssA+D1DIec0BTu6eWt0mccO2u3WDdFBTaLl6mzQ+IipyAM//bJvgimMQPHS",
	"4+tjmDgB+fqtoGH7VmRuRt4i8DzcWJvc0LgOuTE82AvmXKpb3W/QhkDSP2PQMmZAIkJx6tcVu2jWuGe6",
	"n8oD7Whm7mhtW4JcX4D+GWzEmAl72GywUUjah3NeOOlb56QnWXiH6ihf9zsutUk7sS/BpX5JupDc9uWe",
	"mOZgHCMjcWx9oH7BeE4agj0tWpQ6ZpP+yrgu3Aq5sIY10l5bT8IFE4RFOrTVimtO/J4W8/AAtFbA3/92",
	"6PfhJ/Oii8Jb65K/5+LO5hw7nOY/mpetbFeVynW0Ra0unYl8R/NctTYTbU4fm4dee72b1WmYXrZMYuSi",
	"vZWkxllx3aqjpUenNATK0kxB/mepLqQ4lnv/N5ugYKjjNzfAyt42iDyp2LMdhF6YP5dQPCVpkCbkdgK7",
	"neeC36H1ipS3xAoVESSUcQHuTdhDf+bD2Ov7B72x1/LhWhAmbY5WngltzQizWh0IjJFIvKUJmWEAC0qA",
	"wJyIyOZ7xjbPeRyhAGXsY83S7r9qQcZilBKC+qJ9rRb+Su98gULQCCVQ5YMLeSYkvNMrmBBFkzwS3Rjd",
	"FCGNDnOAroU2ZdqihfCoYc5lnG90u9SVtW3cpuNFhLtWH3khYZrFMYSEcUZDEsN3HRt05+prQytY8JBM",
	"dORj85jeD72Wyx9txPrKNZPZRKIC6kJ2ExKlgGxOWIiJNkoRD19I7TbBzqsoCZgdNFJiWaKXf3l18fbq",
	"bDQanL/12p7N0722d3r29ur49OzUa3sfzo9vjgfvj9+81w9+Oh68Nz+fnr0/u7atzD/PTiviKf1IgxVb",
	"s0Ihz1iD5zvPkgkK4FOwdg6svd7kkYsM/Oc7XH70jSPUK00oo4lebL+95s3aXphm6yMPmI3tTXBjNa+m",
	"9N+5jam4Xu0TpvSTLQ+ZIAaTNDaZpQtWbIIZoaALnYaxqlNxQT+VlUCiMskEEy6WXzRPH86sRTjYf/tm",
	"7DXGmVJx0ZhDPaX//Ve9DQOsHDi7201H6UxHOg2Fip9O4IfDV9+ZoklMiQ6z9Zulbdi7FHwSYwKnqAiN",
	"pfEY766vL+H4ciBbxihY23fKQ7l5hCPY2pHX9jKhk5W5Uqk86na1lVCChHcofIpq6nMx60Y87M5VEnfF",
	"NNSdOndQ0ffIdP5oHIqfdEhiXWDhHxW3ZRoe2vw1xKYdpa6suj7Gh6sBCJyiaVpWfYr+rWRrvRd5biZo",
	"p2jbrEjNRtBI0Bk57VWqnVKmDvYbtV5RFTesYDTnQsG8LiuZJQkRy6ZJ5SHuNjm4evXSmMg5Oinolj58",
	"kGgTjtOTIaSCa23tuKAxxggKZQiTjnvsz6iaZxOdvaRWoWT3pcknZEpCbENCVDgvBgu5XEqFyQsJha4n",
	"dOaCZRNgkjDpuABoLf01Iend99JMilDW8EqravJ3nDBlCxLTqEPELNNOxWvv2pJx1ZnyjEW7NyGxKZB2",
	"8BOVSu7eLkWRUKkdeCdCRvEJQ2aMZGqu9z3U4dHuDfM46klDLQiNtaZqw7fjgWp7nzp6zzoLIozu6M0b",
	"nN8cvx+cHl+9/TA8O7/22t75xfVPFx/OtU8+fn91dnz6H2f/fzC6Hnlt7/LsajgYjQYX56dn54Pcm3+4",
	"fnd2fj04Ob42vwzOr8+uzo/fr7j6j6t220wuP5VN5vsdkrip0Gx/z8+/pGwWo+KsAFa8Xe3jH+fIIGNz",
	"09+yDRGVirJZRuXcHdGQZNodmEoNOAWGhfSNrx2zjAkk4dxYjKKimpAlTBCU0JEVTbJYEYY8k/Gy5cOx",
	"Levcz5GN84H9MauFmReD0xOoDfmj8+1ZPKVxbCIydyKhMoVdqoXNpfuTIpI0tXs+NYuvyLOcnJ3zTjX5",
	"Tca7un1VM2KloZ1iLhmtFqtDP8EmF4iEflzBEGsL2loBLFa78YjtUOTN67ur6WrIWSQdWKPlnW9pYYel",
	"IsJakmK6B697vY2DVnzdxkxvtDrIJKNxBGXWUkqm5/f8fifCxZPru+5oF1vsINZyECeUJxd93X5UC732",
	"p7zOayxBAdqWhd9iI3ep+7qX9arWixVr2cZEp6MRTwhtEPdF6oLdlEip5oJns/l6poFKZyT+y6AxnE6z",
	"OL6VGIqmct5OA1R6CHz4o6DKokF+g49YB1tqKfeWGeS5eFGOC3JsoWOzlGitOKBcNcHEJStlgObUQs5v",
	"73D5hXLQrdNsEtNQd9Is7TzPum0Czq+KCE/ZIqCxy3klKW+6MaXMX9ihvludRpNz1P3eDB9RzTxsv91k",
	"HyurKeo3OYXi2qShIVEk5jODoC83Lqw2UODDy5c5xvnyZUnD2G8D4w7KhmARplnQDWwuGsCUxLEp3NiQ",
	"rV550b1HRESdw07/9VfatZvhr9uwtndPWcTv5RcqI5W3rgMD0uqILAKD8KQowEBKh70XEiacx0hYh5FE",
	"R/gic8GGLQO4ssyc6pjAlP/apr5DamPzaT62rQ/owVo+nOKUGPBIcQimJJYYdB3YV1mwm8BWFW2v6FqT",
	"yt4Mj8MQZYOe1s/lb3a4HxondUrlXUMNiaQkpKphMpdESIfdG60+gL3g7ZugG7ylb7RFQ1McJRLe0jcF",
	"b6MNwbV+51q/89//2e/tH7YhGOqfhuan/9I/gdBZDkaQpW0IicQOZRKZpIousCyN9HumNNKGsbd/vakI",
	"0wxNnTk8kTPU4e4dDD+MrnW4atUvmHCuHK3mZliiX22o//LaFayogoSkcm0vdDe3uv/Ah7MFiqUlApgh",
	"DVJCElvi0qpqOBJiYQHmmkcYnXSGh6YQa0bbwPXSG1jgLLpnq+Q7YmjtcqublfZthlJdjNZVpNmobrKQ",
	"2uH5Nqq5FTgNqqurGzsxx7jzg7dTkNU85WFR31s5Zw6Ee7wqZ+11q2JoXL0x3x+TIFFZ9RxW6rmSfr9b",
	"9c5MadMq/iUx4/KUvPo1qPHNcCNg/NWw4kcDiF3xvNWOdkb0boZfB8xbUKEyEkNCwjllCHs37oeh++FR",
	"RI8UvmnbYgsf9tD2Ztow3PId2uQmpFZ6397EHeGH9s5QY+XAPBkwXNu/WhF/e8uRe1FnnQ792N7g5uTy",
	"w7odcL1UxPpU5ExP5Qmg2fcO/boZbsDL+vt9awAJSEyJYclVXjEYi4OjXsgCg+MMf4SIG88WcjbVttJa",
	"lHu+ApTdDEaDi3OLeV19OHf/Gl1fXF6aSloTNmae2n9eHn8YlY834GXl/qwdbu2MdycDuUDpMS6Q7bR5",
	"e8zG74rWfWWv9EFiM6BcT11A/4kkasLNdsadnO1xpqeJC75qrr4xJzxHr25pekuiSDjDtwsvuaFpULDU",
	"9iwD1A5kOWsZu2M6QdFbZr2joWsf9FpVuretzYWGS2BZhgaEQBM6FgzuZe5gn8bgfgIDvuESwd7WGwSP",
	"D86+WNQNTX/von4SM/xmWAt7F8k/iw/ugpBdqOD7r1pHBanbkTKpdFGFTmgyaZO/dcYtTHi0hL3g8mJ0",
	"Dd1FYjjbljl60Cmh6Orbbbif03Cu+7XDaK0N6uYlKI2HFkPLh3PLPC93nAEpWS4FyK3VpEZkd6UEEhrT",
	"dE+FSRFTosI5SEXjGCSySFpbHHweGymPvSP47Pv+w0OQE0jszKUDlgUmhDIrENPSiMGWIagyemeCZ7+O",
	"GTwWc1gi978qbXsLH/rJNXF9bj4vkjr9eZGsMJ8XyY7F70Vib2jVlOx3TnvOzdTXIj6vOPAv5z8/GA8w",
	"5TbOYYqERozurtnpyRAuLcq7RgVxqG/IkyoY3G3cuvX8Vve8BiepOVGGtDcTLlJCc/sERnyBAumMwfEA",
	"TmKeRbCnfVFrzNKYKK3gNlU+PRm2bX+ScmaIrCmy0ZxOVV4El8ab3AylIf5ZjzZmTcjl7OryBI4vB/6Y",
	"jdnLl0Mao1ScoYQD08chyJCnePTyZcFrO7n6cOr6N/8esz1rY7u5eeueYowKW0ZdDBzL+D1EOKUMIx8u",
	"bdGu930P9vIJt3SPY2bdPOzdDGWrvXbFZ+9yTiRCv2VtmLFa2ofK3MjbPszglnFIpa3OCpxRPQ5GgCwy",
	"V2xkjXfY/WDsiZmxrYONtTZSgbFLMlYm4+y0zpjMuC4GNjhwPrAPx3E8ZlOeCdDH0JxOaccwptyJxBac",
	"tUs+vhxYFgoJlWVGoUKGUo6ZHoOwpStmdhlnnVX5aFmgMFt5XRxXdc/BYmnl0m11mjNswwQtvO6mXEhK",
	"6oZjRlmEKTIdrhQ6LK0eGpYLW1DBmVEpMtP/NQw6t6sBEDVmwed83IcuSWl30SdxOif9/GaHDIz8gkXy",
	"yPvaW9tUkEVmdDuiXVwnnGN4J0HLf8wq+10SahRUu7bNAsvE0erY7+W+szgF0B8z7V9bPrzhVQGCwJQL",
	"67tMPJCxCEVsqEYXg9MTU49xM7PMgpiGyCRWDM9xSsI5wr7fW7M79/f3PjGPDfnMtZXd94OTs/PRWWff",
	"7/lzlcQVQpXBoiAHlvNCglaoCuZ75PX9nt/TzXiKjKTUO/IO/J5/6PBhY5Sbd0k/mTWBn1eoMqHVOndB",
	"GEFsqLzT0h7xe5azKK2e7U1pbDdoshwzA1Q63+eyr85k+X+iMFmr+RWRtfU2/V4ebI1ZeQUwKC+0BtoS",
	"6INTiajLeNrsTXE2B5F35GlzcFJeXKreA/95HRMhv2RY9b2WMmIsBtEx6sJcysvjPVN2rzvhoLgD/UuG",
	"huzm9KPip7fe416vfX+iSZYAK5i2uZtWHITZLIOb6P43jZ2QT3aKpjJcHT6yaJV39KrXwPdL7NjeUb/X",
	"207Stdf/rFSMbu33ermDRluKIGkauwJj90/S8ijKiexAvTcBk3H/dQm9X9FOfR4Otw7vSF9/eNo0LPW1",
	"YQJBTb4Gg+GZkjSyRSrK9MzoAiEP7gRhM4Sg7/v9Xi/w7YT7327CH1ZodWb8g283/mXBCATHCHxoe6++",
	"5ZYNXB3ARgfCkkntLPa/3Sy2MNBKMqL5GoKjzjplr1zEVGRmMpbCxH18aHspb0otbFSlLTvDexNGdiYk",
	"vMNoPeK096mLBNvlymOW32yrJMgmeLDpq/atQSVJdh886Lr73v6YDSJMUq7c7e2ARsEREG3FxLKMQmxG",
	"TqPAmTcbVRsKA2WzMQuL+nA1z0SH0TNHDK5RXw7tJHrNLsIK5qS4x7rVR5yYqKxDpKQz7QQbvqfR1sl3",
	"pQamI8v6lyBqtBzt8kZGVTq8AOVzusLBQXFf/kcXZtqbPyAyphNjcFmT1p92eRF8siyqHobu6D5jYK+p",
	"UMdZsBfc81vt05jM6lPr97r5ffEmt2JT7I2u7KPN6FCqNzxafm1vYM9T/ZsiD2tOqP/bDLuiEi6VCh1P",
	"YY+LNtCp1WHHmrb6i1EbqFpR3CIEKrW15X9zJzbUBpnN7KQN/pfLNj/YjgHw7KyendWOzirP4ysfLGnw",
	"Vw/tDTlKThp9LFUxX7yoEdgd23q1XKPtXZ7M5lmlcJZR4DTGUBk6GJLYAl2mnhJyxvSTBVVLk6yWZPKx",
	"5ZJTtdQeU+eQsnRhbi5EQrCW+Rb56j/+8ledL+WVDbcMar4BYri3bZjFfEJiPQ3Ly2jIcceskuSCzXEb",
	"HN1bLFKhdyXn/DeK2t/ljN81TXJsdZPiF2WRyIdrnTbmnyYy1qZd3KusXE8am68ctYGyyJgECfdzNAVM",
	"h1/SXI5LV18oLyTox8aL6u232rPf61mJjk46vd5+XjUohPi7OO3u0rBZCn5KMdR+JiWMhtpV1A+d80ZF",
	"0cCJ+0SLu3IC3f5sO3+fi2+RPdjTpzeqgQpgfpflOdeHwVURJEiuM3YbDAEJ7xi/jzGa2WKp3gYbpeid",
	"ijg6+hqP49UvEBgA2uAo8RIiKkmaIhFjZiIWC9db1wnHEJxz9RPPmI5qdO5uxt7LXbFdR9QCHdJWyIUy",
	"MzwU2Av2e4dB/ZNATeXCMVM8RkFqt/RMmd0QDaE2s30Tgva+7+VQux48r0DZevyUCywKj1Z+wWHvMGg6",
	"ylbmG2PWJs0rX+nWv3/XkLwfNqQPbhuc9HSUUwQ3FmJoPccGz7HBrrGBq+s/Ehu0H/f8zelgJv162ZDK",
	"MjMds/JbeLqLxNIBncPe6aN4293r1z+QvW+ZyNjLffL5ONsZHH67GeQ7oJ2gvZ77bFB2NChvsShfFQq8",
	"W76xSL4MDrkZPoKE2AjnqUhIjrwbLOTMAGAW7EBLaQqaSEzdoIlF5qKjKuVoA0RyM3xGR/410ZEGVskW",
	"kGSFJfkMljzHmP/mYMmaxpdOQRu9L8FLVrr0V9PDMctJfjl5ugA3CrjAFod178YcQWF6YY8qOTas0/xD",
	"slEFXDDUGiAWmHFfE9EZagWCGTNHsC1Z3TW+ZMms3MyA1Il59ab/3hqrsg2OvNmGSabyIjGVpsCtZzNm",
	"zZ/2NQlukcnXPvSrp3pPBf5oubNjZq+4rdEzHdVRusQz/zYTKameWkiSJqmeRsYSIuScxMYr6On9GQW3",
	"VOWcDmokkX82l84YFyi/FmB1M1zFqkAQV7AibAWyKq86mS83HZurUHY34gVKk3YXdDHZKlIVc/vQ+itw",
	"l9+BKEXCeeKIPGNm72zcDHMNyO/32de1FoWchZiq1an80Ov+/W+H/qst8JlhHv82yFkTg7w+v8cxtLFH",
	"HD5TcrcgyaQyofacLNCwSgrMo1yJu2ZptsqQrctHY6+8iP2q9ePKhU6LnjnQLiF3CFT9CvAO9g57PaBT",
	"p/NdQ1Zv1TSphuwZ2dXRvfwz5rUDWdy2y7TtNl/9c5QsG9AWRTmSKd4pvm1NI/n7wgVXCabfFh5sGr2u",
	"/jfDXw0Q1m3DPxUibEOS/2UMf/l3FThsuBxUVPbL982l6epl6bYBIBlkLCVComGZm5eC/F7xmgV4XQjk",
	"OTR8Dg0bQkOjU6sOssa71gY50slIrlvnZ5b/vgnVXAkD1wLLpkLDb4JpLpJvCWeOWbAVrw0KgGMjpjlm",
	"O4CasCumeTN8hjP/beHMm+GvQDLdPZ6d8cu1xO5r4pg3w60Q5s3w9wtilnOzMGYlt/waMGZT7vAIYFL8",
	"3652Ay9vVi4HP4OYz1HE1wQxHwsFdsAx16oEmWzbcmhkg+6mqv+YBc23x+1X24v/xVXFgKxcY97kUr/q",
	"iex9yzxr7ag/g5n/HDBzdSeeQc0vAjUXGxR6Ld3QLc36GtG7pgtlxVW1rjm1rr9NzB8LYJqZl/cfy7LP",
	"SXn/5jH3+0hPej3rndTi7KZmeYj+8eF/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
