// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "https://dcm-project.github.io/problems/already-exists"
	INTERNAL         ErrorType = "https://dcm-project.github.io/problems/internal"
	INVALIDARGUMENT  ErrorType = "https://dcm-project.github.io/problems/invalid-argument"
	NOTFOUND         ErrorType = "https://dcm-project.github.io/problems/not-found"
	PERMISSIONDENIED ErrorType = "https://dcm-project.github.io/problems/permission-denied"
	UNAUTHENTICATED  ErrorType = "https://dcm-project.github.io/problems/unauthenticated"
	UNAVAILABLE      ErrorType = "https://dcm-project.github.io/problems/unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for VMStatus.
const (
	DELETED      VMStatus = "DELETED"
	DELETING     VMStatus = "DELETING"
	FAILED       VMStatus = "FAILED"
	PAUSED       VMStatus = "PAUSED"
	PROVISIONING VMStatus = "PROVISIONING"
	RUNNING      VMStatus = "RUNNING"
	STOPPED      VMStatus = "STOPPED"
	STOPPING     VMStatus = "STOPPING"
)

// Valid indicates whether the value is a known member of the VMStatus enum.
func (e VMStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case DELETING:
		return true
	case FAILED:
		return true
	case PAUSED:
		return true
	case PROVISIONING:
		return true
	case RUNNING:
		return true
	case STOPPED:
		return true
	case STOPPING:
		return true
	default:
		return false
	}
}

// Error RFC 9457 compliant error response (Problem Details for HTTP APIs)
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the error type. Uses the DCM project-controlled https://dcm-project.github.io/problems/* namespace, matching the ecosystem's RFC 9457 migration (see acm-cluster-service-provider and k8s-container-service-provider).
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the error type. Uses the DCM project-controlled https://dcm-project.github.io/problems/* namespace, matching the ecosystem's RFC 9457 migration (see acm-cluster-service-provider and k8s-container-service-provider).
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Detail When unhealthy, distinguishes the cause (token invalid vs. OSAC
	// unreachable — both may be true simultaneously). Absent when
	// healthy.
	//
	//
	// Example: OIDC token invalid; OSAC fulfillment service unreachable
	Detail *string `json:"detail,omitempty"`

	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status HealthStatus `json:"status"`

	// Type Resource type identifier
	//
	// Example: osac-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 0.0.1-dev
	Version *string `json:"version,omitempty"`
}

// HealthStatus Health status
//
// Example: healthy
type HealthStatus string

// OSACVMProviderHints defines model for OSACVMProviderHints.
type OSACVMProviderHints struct {
	// InstanceType Reference to an OSAC `InstanceType` catalog entry. Mapped to OSAC's `spec.instance_type`. **Required** — DD-082, no direct `vcpu`/`memory` fallback exists.
	//
	// Example: standard-4-16
	InstanceType string `json:"instance_type"`

	// TemplateId Reference to the OSAC VM template. Mapped to OSAC's `spec.template`.
	TemplateId string `json:"template_id"`

	// Windows Optional passthrough to OSAC's `spec.is_windows` (renamed here per AEP-140's boolean-naming rule — the SP's own hint schema, not a passthrough of OSAC's field name). Defaults to `false`/omitted.
	Windows *bool `json:"windows,omitempty"`
}

// VMAccess defines model for VMAccess.
type VMAccess struct {
	// SshPublicKey Optional passthrough to OSAC's `spec.ssh_public_key`.
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
}

// VMDisk defines model for VMDisk.
type VMDisk struct {
	// Capacity Parsed per DD-083 (`GB`/`GiB` treated as GiB directly, `TB`/`TiB` ×1024, `MB`/`MiB` ÷1024 rounded up, case-insensitive). E.g. "100GB", "2TB".
	Capacity string `json:"capacity"`

	// Name Exactly one disk MUST be named `boot` (REQ-VMCREATE-030, REQ-VMCREATE-060) — it maps to OSAC's `spec.boot_disk`. Every other disk's `name` is not preserved on translation (SC-M4-002) — OSAC's `ComputeInstanceDisk` has no name field.
	Name string `json:"name"`
}

// VMGuestOS defines model for VMGuestOS.
type VMGuestOS struct {
	// Type Mapped to OSAC's `spec.image.source_ref` (SC-M4-002).
	//
	// Example: rhel-9
	Type string `json:"type"`
}

// VMMemory defines model for VMMemory.
type VMMemory struct {
	// Size Informational only (DD-082) — the SP never translates this to an OSAC field. E.g. "8GB".
	Size string `json:"size"`
}

// VMMetadata defines model for VMMetadata.
type VMMetadata struct {
	// Labels Merged with (not replaced by) the three `dcm.io/*` ownership labels the SP always sets (REQ-VMCREATE-050).
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable VM name. Mapped to OSAC's `metadata.name`.
	Name string `json:"name"`
}

// VMProviderHints defines model for VMProviderHints.
type VMProviderHints struct {
	Osac OSACVMProviderHints `json:"osac"`
}

// VMSpec Service-type-specific input specification for a virtual machine (Virtual Machine generic schema).
type VMSpec struct {
	Access        *VMAccess       `json:"access,omitempty"`
	GuestOs       VMGuestOS       `json:"guest_os"`
	Memory        *VMMemory       `json:"memory,omitempty"`
	Metadata      VMMetadata      `json:"metadata"`
	ProviderHints VMProviderHints `json:"provider_hints"`
	Storage       VMStorage       `json:"storage"`
	Vcpu          *VMVCPU         `json:"vcpu,omitempty"`
}

// VMStatus DCM's full canonical 8-value VM status vocabulary (DD-081) — a separate vocabulary from Cluster's 7-value one; do not conflate the two.
type VMStatus string

// VMStorage defines model for VMStorage.
type VMStorage struct {
	Disks []VMDisk `json:"disks"`
}

// VMVCPU defines model for VMVCPU.
type VMVCPU struct {
	// Count Informational only (DD-082) — the SP never translates this to an OSAC field. Use `provider_hints.osac.instance_type` instead.
	Count int `json:"count"`
}

// VirtualMachine A virtual machine resource managed by OSAC.
type VirtualMachine struct {
	CreateTime *time.Time `json:"create_time,omitempty"`

	// ExternalIpAddress Echoes OSAC's `status.external_ip_address` exactly (empty string when unknown — REQ-VMGET-030). Populated identically on Get and every List entry (REQ-VMLIST-030).
	ExternalIpAddress *string `json:"external_ip_address,omitempty"`

	// Id Same value as OSAC's `ComputeInstance.id` (DD-080's ID Mapping note).
	Id *string `json:"id,omitempty"`

	// InternalIpAddress Echoes OSAC's `status.internal_ip_address` exactly (empty string when unknown — REQ-VMGET-030). Populated identically on Get and every List entry (REQ-VMLIST-030).
	InternalIpAddress *string `json:"internal_ip_address,omitempty"`

	// Path Resource path for this VM
	//
	// Example: vms/123e4567-e89b-12d3-a456-426614174000
	Path *string `json:"path,omitempty"`

	// Spec Request-only (DD-085): present when this schema is used as the Create request body (`POST /vms`'s AEP-133-compliant request body, which is this same `VirtualMachine` resource type). Never populated in a Get/List response — control-plane's own actual wire dispatch still sends only `{"spec": {...}}` in the body, so this remains the only body field it ever sets.
	Spec *VMSpec `json:"spec,omitempty"`

	// Status DCM's full canonical 8-value VM status vocabulary (DD-081) — a separate vocabulary from Cluster's 7-value one; do not conflate the two.
	Status VMStatus `json:"status"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string    `json:"status_message,omitempty"`
	UpdateTime    *time.Time `json:"update_time,omitempty"`
}

// VirtualMachineList AEP-132 pagination wrapper.
type VirtualMachineList struct {
	// NextPageToken Empty/absent exactly when there are no further results (REQ-VMLIST-040).
	NextPageToken *string          `json:"next_page_token,omitempty"`
	Results       []VirtualMachine `json:"results"`
}

// VMIdPath defines model for VMIdPath.
type VMIdPath = string

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	// PageToken Opaque pagination token from a previous response's `next_page_token`.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Caller-assigned resource identifier, set as OSAC's own `ComputeInstance.id` (REQ-VMCREATE-020). Schema-optional per AEP-133 ("a create operation must not have any required parameters other than path parameters" — DD-085); REQ-VMCREATE-010/060 still make it a hard runtime requirement, enforced by request validation (400 if absent/empty) rather than this field's own `required` flag, since control-plane always supplies it and this SP does not auto-generate ids.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VirtualMachine
