// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "ALREADY_EXISTS"
	INTERNAL         ErrorType = "INTERNAL"
	INVALIDARGUMENT  ErrorType = "INVALID_ARGUMENT"
	NOTFOUND         ErrorType = "NOT_FOUND"
	PERMISSIONDENIED ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED  ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE      ErrorType = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type Short error code identifying the error type. Despite the uri-reference format (RFC 7807 nominally expects a URI), this repo matches the DCM service provider ecosystem's established convention (see k8s-container-service-provider and acm-cluster-service-provider) of bare short codes rather than real URIs.
	Type ErrorType `json:"type"`
}

// ErrorType Short error code identifying the error type. Despite the uri-reference format (RFC 7807 nominally expects a URI), this repo matches the DCM service provider ecosystem's established convention (see k8s-container-service-provider and acm-cluster-service-provider) of bare short codes rather than real URIs.
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Detail When unhealthy, distinguishes the cause (token invalid vs. OSAC
	// unreachable — both may be true simultaneously). Absent when
	// healthy.
	//
	//
	// Example: OIDC token invalid; OSAC fulfillment service unreachable
	Detail *string `json:"detail,omitempty"`

	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status HealthStatus `json:"status"`

	// Type Resource type identifier
	//
	// Example: osac-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 0.0.1-dev
	Version *string `json:"version,omitempty"`
}

// HealthStatus Health status
//
// Example: healthy
type HealthStatus string
