// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ClusterStatus.
const (
	ClusterStatusACTIVE      ClusterStatus = "ACTIVE"
	ClusterStatusDEGRADED    ClusterStatus = "DEGRADED"
	ClusterStatusDELETED     ClusterStatus = "DELETED"
	ClusterStatusDELETING    ClusterStatus = "DELETING"
	ClusterStatusFAILED      ClusterStatus = "FAILED"
	ClusterStatusPROGRESSING ClusterStatus = "PROGRESSING"
	ClusterStatusUNAVAILABLE ClusterStatus = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ClusterStatus enum.
func (e ClusterStatus) Valid() bool {
	switch e {
	case ClusterStatusACTIVE:
		return true
	case ClusterStatusDEGRADED:
		return true
	case ClusterStatusDELETED:
		return true
	case ClusterStatusDELETING:
		return true
	case ClusterStatusFAILED:
		return true
	case ClusterStatusPROGRESSING:
		return true
	case ClusterStatusUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ErrorTypeALREADYEXISTS    ErrorType = "https://dcm-project.github.io/problems/already-exists"
	ErrorTypeINTERNAL         ErrorType = "https://dcm-project.github.io/problems/internal"
	ErrorTypeINVALIDARGUMENT  ErrorType = "https://dcm-project.github.io/problems/invalid-argument"
	ErrorTypeNOTFOUND         ErrorType = "https://dcm-project.github.io/problems/not-found"
	ErrorTypePERMISSIONDENIED ErrorType = "https://dcm-project.github.io/problems/permission-denied"
	ErrorTypeUNAUTHENTICATED  ErrorType = "https://dcm-project.github.io/problems/unauthenticated"
	ErrorTypeUNAVAILABLE      ErrorType = "https://dcm-project.github.io/problems/unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ErrorTypeALREADYEXISTS:
		return true
	case ErrorTypeINTERNAL:
		return true
	case ErrorTypeINVALIDARGUMENT:
		return true
	case ErrorTypeNOTFOUND:
		return true
	case ErrorTypePERMISSIONDENIED:
		return true
	case ErrorTypeUNAUTHENTICATED:
		return true
	case ErrorTypeUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for VMStatus.
const (
	VMStatusDELETED      VMStatus = "DELETED"
	VMStatusDELETING     VMStatus = "DELETING"
	VMStatusFAILED       VMStatus = "FAILED"
	VMStatusPAUSED       VMStatus = "PAUSED"
	VMStatusPROVISIONING VMStatus = "PROVISIONING"
	VMStatusRUNNING      VMStatus = "RUNNING"
	VMStatusSTOPPED      VMStatus = "STOPPED"
	VMStatusSTOPPING     VMStatus = "STOPPING"
)

// Valid indicates whether the value is a known member of the VMStatus enum.
func (e VMStatus) Valid() bool {
	switch e {
	case VMStatusDELETED:
		return true
	case VMStatusDELETING:
		return true
	case VMStatusFAILED:
		return true
	case VMStatusPAUSED:
		return true
	case VMStatusPROVISIONING:
		return true
	case VMStatusRUNNING:
		return true
	case VMStatusSTOPPED:
		return true
	case VMStatusSTOPPING:
		return true
	default:
		return false
	}
}

// Cluster A cluster resource managed by OSAC.
type Cluster struct {
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Same value as OSAC's `Cluster.id` (DD-080's ID Mapping note).
	Id *string `json:"id,omitempty"`

	// Kubeconfig Base64-encoded kubeconfig. Populated only when `status` is exactly `ACTIVE` (REQ-GET-020/030); always empty on List entries (REQ-LIST-030).
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// NodeSets Echoes OSAC's `status.node_sets` map directly — no `ready`/`total` computation, since OSAC's `ClusterNodeSet` has no such field (SC-M3-002).
	NodeSets *map[string]ClusterNodeSet `json:"node_sets,omitempty"`

	// Path Resource path for this cluster
	//
	// Example: clusters/123e4567-e89b-12d3-a456-426614174000
	Path *string `json:"path,omitempty"`

	// Spec Request-only (DD-113): only field `control-plane` populates on Create; never present on Get/List. Required per OpenAPI 3.0's `writeOnly`+`required` (request-only), mirroring `status`'s `readOnly`+`required` (response-only) above — both generate as pointers (`omitempty`) either way, so neither forces a spurious empty value on the other's side. Also enforced at the handler level (REQ-CREATE-060).
	Spec   *ClusterSpec   `json:"spec,omitempty"`
	Status *ClusterStatus `json:"status,omitempty"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string    `json:"status_message,omitempty"`
	UpdateTime    *time.Time `json:"update_time,omitempty"`

	// Version Echoed from the Create request's `spec.version`. Create response only — omitted on Get/List (SC-M3-002).
	Version *string `json:"version,omitempty"`
}

// ClusterList AEP-132 pagination wrapper.
type ClusterList struct {
	// NextPageToken Empty/absent exactly when there are no further results (REQ-LIST-040).
	NextPageToken *string   `json:"next_page_token,omitempty"`
	Results       []Cluster `json:"results"`
}

// ClusterMetadata defines model for ClusterMetadata.
type ClusterMetadata struct {
	// Labels Merged with (not replaced by) the three `dcm.io/*` ownership labels the SP always sets (REQ-CREATE-030).
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable cluster name. Mapped to OSAC's `spec.metadata.name`.
	Name string `json:"name"`
}

// ClusterNodeSet Mirrors OSAC's `ClusterNodeSet` (`host_type`, `size`) — see SC-M3-002.
type ClusterNodeSet struct {
	HostType *string `json:"host_type,omitempty"`
	Size     *int    `json:"size,omitempty"`
}

// ClusterNodes Node configuration for the cluster. No `control_plane` bucket: OSAC's Hosted Control Planes manage the control plane internally, so the generic schema's `nodes.control_plane` has no corresponding OSAC field and is not sent (see M3 spec §4.1 Field Mapping).
type ClusterNodes struct {
	Worker ClusterWorkerNodes `json:"worker"`
}

// ClusterProviderHints defines model for ClusterProviderHints.
type ClusterProviderHints struct {
	Osac OSACProviderHints `json:"osac"`
}

// ClusterSpec Service-type-specific input specification for a cluster (Kubernetes Cluster generic schema).
type ClusterSpec struct {
	Metadata ClusterMetadata `json:"metadata"`

	// Nodes Node configuration for the cluster. No `control_plane` bucket: OSAC's Hosted Control Planes manage the control plane internally, so the generic schema's `nodes.control_plane` has no corresponding OSAC field and is not sent (see M3 spec §4.1 Field Mapping).
	Nodes         ClusterNodes         `json:"nodes"`
	ProviderHints ClusterProviderHints `json:"provider_hints"`

	// Version Kubernetes minor version (e.g. "1.30"). Translated internally to an OSAC `release_image` via a hardcoded placeholder table (REQ-CREATE-025) unless `provider_hints.osac.release_image` overrides it. Echoed back verbatim on the Create response only — Get/List omit it (SC-M3-002).
	//
	// Example: 1.30
	Version string `json:"version"`
}

// ClusterStatus DCM's full canonical 7-value Cluster status vocabulary (DD-090) — not the 5-value subset in the osac-sp enhancement doc's own Status Mapping table.
type ClusterStatus string

// ClusterWorkerNodes defines model for ClusterWorkerNodes.
type ClusterWorkerNodes struct {
	// Count Number of worker nodes. Mapped to OSAC's `spec.node_sets[key].size`.
	Count int `json:"count"`

	// Cpu Informational only (REQ-CREATE-070) — `host_type` is fixed by the template; the SP never derives an OSAC field from this.
	Cpu *int `json:"cpu,omitempty"`

	// Memory Informational only (REQ-CREATE-070). E.g. "32GB".
	Memory *string `json:"memory,omitempty"`

	// Storage Informational only (REQ-CREATE-070). E.g. "250GB".
	Storage *string `json:"storage,omitempty"`
}

// Error RFC 9457 compliant error response (Problem Details for HTTP APIs)
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the error type. Uses the DCM project-controlled https://dcm-project.github.io/problems/* namespace, matching the ecosystem's RFC 9457 migration (see acm-cluster-service-provider and k8s-container-service-provider).
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the error type. Uses the DCM project-controlled https://dcm-project.github.io/problems/* namespace, matching the ecosystem's RFC 9457 migration (see acm-cluster-service-provider and k8s-container-service-provider).
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Detail When unhealthy, distinguishes the cause (token invalid vs. OSAC
	// unreachable — both may be true simultaneously). Absent when
	// healthy.
	//
	//
	// Example: OIDC token invalid; OSAC fulfillment service unreachable
	Detail *string `json:"detail,omitempty"`

	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status HealthStatus `json:"status"`

	// Type Resource type identifier
	//
	// Example: osac-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 0.0.1-dev
	Version *string `json:"version,omitempty"`
}

// HealthStatus Health status
//
// Example: healthy
type HealthStatus string

// OSACProviderHints defines model for OSACProviderHints.
type OSACProviderHints struct {
	// BaseDomain Optional passthrough to OSAC's `spec.network.*`.
	BaseDomain *string `json:"base_domain,omitempty"`

	// PullSecret Optional passthrough to OSAC's `spec.pull_secret`. Write-only.
	PullSecret *string `json:"pull_secret,omitempty"`

	// ReleaseImage Optional override for the `version`-derived `release_image` translation (REQ-CREATE-025).
	ReleaseImage *string `json:"release_image,omitempty"`

	// SshKey Optional passthrough to OSAC's `spec.ssh_public_key`.
	SshKey *string `json:"ssh_key,omitempty"`

	// TemplateId Reference to the OSAC cluster template. Mapped to OSAC's `spec.template`.
	TemplateId string `json:"template_id"`
}

// OSACVMProviderHints defines model for OSACVMProviderHints.
type OSACVMProviderHints struct {
	// InstanceType Reference to an OSAC `InstanceType` catalog entry. Mapped to OSAC's `spec.instance_type`. **Required** — DD-122, no direct `vcpu`/`memory` fallback exists.
	//
	// Example: standard-4-16
	InstanceType string `json:"instance_type"`

	// TemplateId Reference to the OSAC VM template. Mapped to OSAC's `spec.template`.
	TemplateId string `json:"template_id"`

	// Windows Optional passthrough to OSAC's `spec.is_windows` (renamed here per AEP-140's boolean-naming rule — the SP's own hint schema, not a passthrough of OSAC's field name). Defaults to `false`/omitted.
	Windows *bool `json:"windows,omitempty"`
}

// VMAccess defines model for VMAccess.
type VMAccess struct {
	// SshPublicKey Optional passthrough to OSAC's `spec.ssh_public_key`.
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
}

// VMDisk defines model for VMDisk.
type VMDisk struct {
	// Capacity Parsed per DD-123 (`GB`/`GiB` treated as GiB directly, `TB`/`TiB` ×1024, `MB`/`MiB` ÷1024 rounded up, case-insensitive). E.g. "100GB", "2TB".
	Capacity string `json:"capacity"`

	// Name Exactly one disk MUST be named `boot` (REQ-VMCREATE-030, REQ-VMCREATE-060) — it maps to OSAC's `spec.boot_disk`. Every other disk's `name` is not preserved on translation (SC-M4-002) — OSAC's `ComputeInstanceDisk` has no name field.
	Name string `json:"name"`
}

// VMGuestOS defines model for VMGuestOS.
type VMGuestOS struct {
	// Type Mapped to OSAC's `spec.image.source_ref` (SC-M4-002).
	//
	// Example: rhel-9
	Type string `json:"type"`
}

// VMMemory defines model for VMMemory.
type VMMemory struct {
	// Size Informational only (DD-122) — the SP never translates this to an OSAC field. E.g. "8GB".
	Size string `json:"size"`
}

// VMMetadata defines model for VMMetadata.
type VMMetadata struct {
	// Labels Merged with (not replaced by) the three `dcm.io/*` ownership labels the SP always sets (REQ-VMCREATE-050).
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable VM name. Mapped to OSAC's `metadata.name`.
	Name string `json:"name"`
}

// VMProviderHints defines model for VMProviderHints.
type VMProviderHints struct {
	Osac OSACVMProviderHints `json:"osac"`
}

// VMSpec Service-type-specific input specification for a virtual machine (Virtual Machine generic schema).
type VMSpec struct {
	Access        *VMAccess       `json:"access,omitempty"`
	GuestOs       VMGuestOS       `json:"guest_os"`
	Memory        *VMMemory       `json:"memory,omitempty"`
	Metadata      VMMetadata      `json:"metadata"`
	ProviderHints VMProviderHints `json:"provider_hints"`
	Storage       VMStorage       `json:"storage"`
	Vcpu          *VMVCPU         `json:"vcpu,omitempty"`
}

// VMStatus DCM's full canonical 8-value VM status vocabulary (DD-121) — a separate vocabulary from Cluster's 7-value one; do not conflate the two.
type VMStatus string

// VMStorage defines model for VMStorage.
type VMStorage struct {
	Disks []VMDisk `json:"disks"`
}

// VMVCPU defines model for VMVCPU.
type VMVCPU struct {
	// Count Informational only (DD-122) — the SP never translates this to an OSAC field. Use `provider_hints.osac.instance_type` instead.
	Count int `json:"count"`
}

// VirtualMachine A virtual machine resource managed by OSAC.
type VirtualMachine struct {
	CreateTime *time.Time `json:"create_time,omitempty"`

	// ExternalIpAddress Echoes OSAC's `status.external_ip_address` exactly (empty string when unknown — REQ-VMGET-030). Populated identically on Get and every List entry (REQ-VMLIST-030).
	ExternalIpAddress *string `json:"external_ip_address,omitempty"`

	// Id Same value as OSAC's `ComputeInstance.id` (DD-120's ID Mapping note).
	Id *string `json:"id,omitempty"`

	// InternalIpAddress Echoes OSAC's `status.internal_ip_address` exactly (empty string when unknown — REQ-VMGET-030). Populated identically on Get and every List entry (REQ-VMLIST-030).
	InternalIpAddress *string `json:"internal_ip_address,omitempty"`

	// Path Resource path for this VM
	//
	// Example: vms/123e4567-e89b-12d3-a456-426614174000
	Path *string `json:"path,omitempty"`

	// Spec Request-only (DD-125): present when this schema is used as the Create request body (`POST /vms`'s AEP-133-compliant request body, which is this same `VirtualMachine` resource type). Never populated in a Get/List response — control-plane's own actual wire dispatch still sends only `{"spec": {...}}` in the body, so this remains the only body field it ever sets.
	Spec *VMSpec `json:"spec,omitempty"`

	// Status DCM's full canonical 8-value VM status vocabulary (DD-121) — a separate vocabulary from Cluster's 7-value one; do not conflate the two.
	Status VMStatus `json:"status"`

	// StatusMessage Human-readable message about the current status
	StatusMessage *string    `json:"status_message,omitempty"`
	UpdateTime    *time.Time `json:"update_time,omitempty"`
}

// VirtualMachineList AEP-132 pagination wrapper.
type VirtualMachineList struct {
	// NextPageToken Empty/absent exactly when there are no further results (REQ-VMLIST-040).
	NextPageToken *string          `json:"next_page_token,omitempty"`
	Results       []VirtualMachine `json:"results"`
}

// ClusterIdPath defines model for ClusterIdPath.
type ClusterIdPath = string

// VMIdPath defines model for VMIdPath.
type VMIdPath = string

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	// PageToken Opaque pagination token from a previous response's `next_page_token`.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Caller-assigned resource identifier, set as OSAC's own `Cluster.id` (REQ-CREATE-020). Schema-optional per AEP-133 (DD-113); still a hard runtime requirement, enforced by request validation, not this field's `required` flag (REQ-CREATE-010/060).
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	// PageToken Opaque pagination token from a previous response's `next_page_token`.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Caller-assigned resource identifier, set as OSAC's own `ComputeInstance.id` (REQ-VMCREATE-020). Schema-optional per AEP-133 ("a create operation must not have any required parameters other than path parameters" — DD-125); REQ-VMCREATE-010/060 still make it a hard runtime requirement, enforced by request validation (400 if absent/empty) rather than this field's own `required` flag, since control-plane always supplies it and this SP does not auto-generate ids.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = Cluster

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VirtualMachine
