//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/tenants_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tenants_Create_FullMethodName = "/osac.private.v1.Tenants/Create"
	Tenants_Get_FullMethodName    = "/osac.private.v1.Tenants/Get"
)

// TenantsClient is the client API for Tenants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsClient interface {
	Create(ctx context.Context, in *TenantsCreateRequest, opts ...grpc.CallOption) (*TenantsCreateResponse, error)
	Get(ctx context.Context, in *TenantsGetRequest, opts ...grpc.CallOption) (*TenantsGetResponse, error)
}

type tenantsClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsClient(cc grpc.ClientConnInterface) TenantsClient {
	return &tenantsClient{cc}
}

func (c *tenantsClient) Create(ctx context.Context, in *TenantsCreateRequest, opts ...grpc.CallOption) (*TenantsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantsCreateResponse)
	err := c.cc.Invoke(ctx, Tenants_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) Get(ctx context.Context, in *TenantsGetRequest, opts ...grpc.CallOption) (*TenantsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantsGetResponse)
	err := c.cc.Invoke(ctx, Tenants_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServer is the server API for Tenants service.
// All implementations must embed UnimplementedTenantsServer
// for forward compatibility.
type TenantsServer interface {
	Create(context.Context, *TenantsCreateRequest) (*TenantsCreateResponse, error)
	Get(context.Context, *TenantsGetRequest) (*TenantsGetResponse, error)
	mustEmbedUnimplementedTenantsServer()
}

// UnimplementedTenantsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantsServer struct{}

func (UnimplementedTenantsServer) Create(context.Context, *TenantsCreateRequest) (*TenantsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTenantsServer) Get(context.Context, *TenantsGetRequest) (*TenantsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTenantsServer) mustEmbedUnimplementedTenantsServer() {}
func (UnimplementedTenantsServer) testEmbeddedByValue()                 {}

// UnsafeTenantsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServer will
// result in compilation errors.
type UnsafeTenantsServer interface {
	mustEmbedUnimplementedTenantsServer()
}

func RegisterTenantsServer(s grpc.ServiceRegistrar, srv TenantsServer) {
	// If the following call pancis, it indicates UnimplementedTenantsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tenants_ServiceDesc, srv)
}

func _Tenants_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).Create(ctx, req.(*TenantsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).Get(ctx, req.(*TenantsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tenants_ServiceDesc is the grpc.ServiceDesc for Tenants service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tenants_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.Tenants",
	HandlerType: (*TenantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tenants_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Tenants_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/tenants_service.proto",
}
