//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package osac.private.v1;

import "buf/validate/validate.proto";
import "cleanapi/cleanapi.proto";
import "google/protobuf/timestamp.proto";

option (cleanapi.file).package = "osac.public.v1";

// Metadata common to all kinds of objects.
message Metadata {
  google.protobuf.Timestamp creation_timestamp = 1;
  google.protobuf.Timestamp deletion_timestamp = 2;
  string creator = 3;
  string tenant = 4;
  string name = 5 [(buf.validate.field).string = {
    min_len: 1
    max_len: 63
    pattern: "^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$"
  }];
  map<string, string> labels = 6;
  map<string, string> annotations = 7;
  int32 version = 8;
  string project = 9;
  string display_name = 10 [(buf.validate.field).string = {max_len: 63}];
  string description = 11 [(buf.validate.field).string = {max_len: 256}];
  repeated string finalizers = 12 [(cleanapi.field).private = true];
}
