//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package osac.private.v1;

import "cleanapi/cleanapi.proto";
import "google/api/annotations.proto";
import "google/protobuf/field_mask.proto";
import "osac/private/v1/secret_type.proto";

option (cleanapi.file).http_route_prefix_map = "private:fulfillment";
option (cleanapi.file).package = "osac.public.v1";

message SecretsListRequest {
  optional int32 offset = 1;
  optional int32 limit = 2;
  optional string filter = 3;
  optional string order = 4;
}

message SecretsListResponse {
  int32 size = 1;
  int32 total = 2;
  repeated Secret items = 3;
}

message SecretsGetRequest {
  string id = 1;
}

message SecretsGetResponse {
  Secret object = 1;
}

message SecretsCreateRequest {
  Secret object = 1;
}

message SecretsCreateResponse {
  Secret object = 1;
}

message SecretsUpdateRequest {
  Secret object = 1;
  google.protobuf.FieldMask update_mask = 2;
  bool lock = 3;
}

message SecretsUpdateResponse {
  Secret object = 1;
}

message SecretsDeleteRequest {
  string id = 1;
}

message SecretsDeleteResponse {}

message SecretsSignalRequest {
  option (cleanapi.message).private = true;
  string id = 1;
}

message SecretsSignalResponse {
  option (cleanapi.message).private = true;
}

// Service for managing secrets through the private API.
service Secrets {
  rpc List(SecretsListRequest) returns (SecretsListResponse) {
    option (google.api.http) = {get: "/api/private/v1/secrets"};
  }

  rpc Get(SecretsGetRequest) returns (SecretsGetResponse) {
    option (google.api.http) = {
      get: "/api/private/v1/secrets/{id}"
      response_body: "object"
    };
  }

  rpc Create(SecretsCreateRequest) returns (SecretsCreateResponse) {
    option (google.api.http) = {
      post: "/api/private/v1/secrets"
      body: "object"
      response_body: "object"
    };
  }

  rpc Update(SecretsUpdateRequest) returns (SecretsUpdateResponse) {
    option (google.api.http) = {
      patch: "/api/private/v1/secrets/{object.id}"
      body: "object"
      response_body: "object"
    };
  }

  rpc Delete(SecretsDeleteRequest) returns (SecretsDeleteResponse) {
    option (google.api.http) = {delete: "/api/private/v1/secrets/{id}"};
  }

  rpc Signal(SecretsSignalRequest) returns (SecretsSignalResponse) {
    option (cleanapi.method).private = true;
  }
}
