// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	. "github.com/dcm-project/osac-service-provider/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListClusters List clusters
	//
	// Returns a paginated list of clusters owned by this SP (filtered by
	// the `dcm.io/managed-by=dcm` ownership label — REQ-LIST-010). Never
	// populates `kubeconfig` on any entry (REQ-LIST-030).
	//
	// Corresponds with GET /api/v1alpha1/clusters (the `ListClusters` operationId).
	ListClusters(ctx context.Context, params *ListClustersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateClusterWithBody Create a cluster
	//
	// Creates a new OSAC-backed OpenShift cluster. `control-plane`
	// dispatches this with the resource `id` as a query parameter (its
	// own generated identifier) and a body containing only `spec`
	// (DD-080) — the request body schema is this same `Cluster` resource
	// type (AEP-133-compliant, DD-113), but `spec` is its only field
	// `control-plane` ever actually populates on the wire; every other
	// `Cluster` field is absent from that request and simply unmarshals
	// to its zero value, which this handler ignores. Idempotent on `id`:
	// a retry with the same `id` returns the existing cluster's current
	// state rather than an error (REQ-CREATE-040/DD-100).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
	CreateClusterWithBody(ctx context.Context, params *CreateClusterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCluster Create a cluster
	//
	// Creates a new OSAC-backed OpenShift cluster. `control-plane`
	// dispatches this with the resource `id` as a query parameter (its
	// own generated identifier) and a body containing only `spec`
	// (DD-080) — the request body schema is this same `Cluster` resource
	// type (AEP-133-compliant, DD-113), but `spec` is its only field
	// `control-plane` ever actually populates on the wire; every other
	// `Cluster` field is absent from that request and simply unmarshals
	// to its zero value, which this handler ignores. Idempotent on `id`:
	// a retry with the same `id` returns the existing cluster's current
	// state rather than an error (REQ-CREATE-040/DD-100).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
	CreateCluster(ctx context.Context, params *CreateClusterParams, body CreateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClustersHealth Cluster Provider Health Check
	//
	// Returns the health status of the service provider's `cluster`
	// registration, reflecting real OSAC gRPC connectivity and OIDC token
	// validity. Reports the same status as `/api/v1alpha1/vms/health` —
	// this SP's health is a single, global condition (see DD-010 in the
	// Milestone 1 spec).
	//
	// Corresponds with GET /api/v1alpha1/clusters/health (the `GetClustersHealth` operationId).
	GetClustersHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCluster Delete a cluster
	//
	// Deletes a cluster. Returns as soon as OSAC acknowledges the
	// request — does not poll for the cluster to actually disappear
	// (REQ-DELETE-040). A `NotFound` from OSAC (already deleted) is
	// treated as success (`204`), mirroring `control-plane`'s own
	// tolerance for this exact case (REQ-DELETE-020/DD-080) — this
	// endpoint therefore never returns `404`.
	//
	// Corresponds with DELETE /api/v1alpha1/clusters/{clusterId} (the `DeleteCluster` operationId).
	DeleteCluster(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCluster Get cluster details
	//
	// Returns the cluster's current status. `kubeconfig` is populated
	// only when the mapped status is exactly `ACTIVE` (REQ-GET-020/030).
	//
	// Corresponds with GET /api/v1alpha1/clusters/{clusterId} (the `GetCluster` operationId).
	GetCluster(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVMsHealth VM Provider Health Check
	//
	// Returns the health status of the service provider's `vm`
	// registration, reflecting real OSAC gRPC connectivity and OIDC token
	// validity. Reports the same status as
	// `/api/v1alpha1/clusters/health` — this SP's health is a single,
	// global condition (see DD-010 in the Milestone 1 spec).
	//
	// Corresponds with GET /api/v1alpha1/vms/health (the `GetVMsHealth` operationId).
	GetVMsHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListClusters List clusters
//
// Returns a paginated list of clusters owned by this SP (filtered by
// the `dcm.io/managed-by=dcm` ownership label — REQ-LIST-010). Never
// populates `kubeconfig` on any entry (REQ-LIST-030).
//
// Corresponds with GET /api/v1alpha1/clusters (the `ListClusters` operationId).
func (c *Client) ListClusters(ctx context.Context, params *ListClustersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListClustersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateClusterWithBody Create a cluster
//
// Creates a new OSAC-backed OpenShift cluster. `control-plane`
// dispatches this with the resource `id` as a query parameter (its
// own generated identifier) and a body containing only `spec`
// (DD-080) — the request body schema is this same `Cluster` resource
// type (AEP-133-compliant, DD-113), but `spec` is its only field
// `control-plane` ever actually populates on the wire; every other
// `Cluster` field is absent from that request and simply unmarshals
// to its zero value, which this handler ignores. Idempotent on `id`:
// a retry with the same `id` returns the existing cluster's current
// state rather than an error (REQ-CREATE-040/DD-100).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
func (c *Client) CreateClusterWithBody(ctx context.Context, params *CreateClusterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateClusterRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCluster Create a cluster
//
// Creates a new OSAC-backed OpenShift cluster. `control-plane`
// dispatches this with the resource `id` as a query parameter (its
// own generated identifier) and a body containing only `spec`
// (DD-080) — the request body schema is this same `Cluster` resource
// type (AEP-133-compliant, DD-113), but `spec` is its only field
// `control-plane` ever actually populates on the wire; every other
// `Cluster` field is absent from that request and simply unmarshals
// to its zero value, which this handler ignores. Idempotent on `id`:
// a retry with the same `id` returns the existing cluster's current
// state rather than an error (REQ-CREATE-040/DD-100).
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
func (c *Client) CreateCluster(ctx context.Context, params *CreateClusterParams, body CreateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateClusterRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetClustersHealth Cluster Provider Health Check
//
// Returns the health status of the service provider's `cluster`
// registration, reflecting real OSAC gRPC connectivity and OIDC token
// validity. Reports the same status as `/api/v1alpha1/vms/health` —
// this SP's health is a single, global condition (see DD-010 in the
// Milestone 1 spec).
//
// Corresponds with GET /api/v1alpha1/clusters/health (the `GetClustersHealth` operationId).
func (c *Client) GetClustersHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteCluster Delete a cluster
//
// Deletes a cluster. Returns as soon as OSAC acknowledges the
// request — does not poll for the cluster to actually disappear
// (REQ-DELETE-040). A `NotFound` from OSAC (already deleted) is
// treated as success (`204`), mirroring `control-plane`'s own
// tolerance for this exact case (REQ-DELETE-020/DD-080) — this
// endpoint therefore never returns `404`.
//
// Corresponds with DELETE /api/v1alpha1/clusters/{clusterId} (the `DeleteCluster` operationId).
func (c *Client) DeleteCluster(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteClusterRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCluster Get cluster details
//
// Returns the cluster's current status. `kubeconfig` is populated
// only when the mapped status is exactly `ACTIVE` (REQ-GET-020/030).
//
// Corresponds with GET /api/v1alpha1/clusters/{clusterId} (the `GetCluster` operationId).
func (c *Client) GetCluster(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClusterRequest(c.Server, clusterId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVMsHealth VM Provider Health Check
//
// Returns the health status of the service provider's `vm`
// registration, reflecting real OSAC gRPC connectivity and OIDC token
// validity. Reports the same status as
// `/api/v1alpha1/clusters/health` — this SP's health is a single,
// global condition (see DD-010 in the Milestone 1 spec).
//
// Corresponds with GET /api/v1alpha1/vms/health (the `GetVMsHealth` operationId).
func (c *Client) GetVMsHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVMsHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListClustersRequest constructs an http.Request for the ListClusters method
func NewListClustersRequest(server string, params *ListClustersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.MaxPageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_page_size", *params.MaxPageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateClusterRequest calls the generic CreateCluster builder with application/json body
func NewCreateClusterRequest(server string, params *CreateClusterParams, body CreateClusterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateClusterRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateClusterRequestWithBody constructs an http.Request for the CreateCluster method, with any body, and a specified content type
func NewCreateClusterRequestWithBody(server string, params *CreateClusterParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", *params.Id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetClustersHealthRequest constructs an http.Request for the GetClustersHealth method
func NewGetClustersHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/clusters/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteClusterRequest constructs an http.Request for the DeleteCluster method
func NewDeleteClusterRequest(server string, clusterId ClusterIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clusterId", clusterId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClusterRequest constructs an http.Request for the GetCluster method
func NewGetClusterRequest(server string, clusterId ClusterIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "clusterId", clusterId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVMsHealthRequest constructs an http.Request for the GetVMsHealth method
func NewGetVMsHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/vms/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListClustersWithResponse List clusters
	//
	// Returns a paginated list of clusters owned by this SP (filtered by
	// the `dcm.io/managed-by=dcm` ownership label — REQ-LIST-010). Never
	// populates `kubeconfig` on any entry (REQ-LIST-030).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1alpha1/clusters (the `ListClusters` operationId).
	ListClustersWithResponse(ctx context.Context, params *ListClustersParams, reqEditors ...RequestEditorFn) (*ListClustersResponse, error)

	// CreateClusterWithBodyWithResponse Create a cluster
	//
	// Creates a new OSAC-backed OpenShift cluster. `control-plane`
	// dispatches this with the resource `id` as a query parameter (its
	// own generated identifier) and a body containing only `spec`
	// (DD-080) — the request body schema is this same `Cluster` resource
	// type (AEP-133-compliant, DD-113), but `spec` is its only field
	// `control-plane` ever actually populates on the wire; every other
	// `Cluster` field is absent from that request and simply unmarshals
	// to its zero value, which this handler ignores. Idempotent on `id`:
	// a retry with the same `id` returns the existing cluster's current
	// state rather than an error (REQ-CREATE-040/DD-100).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
	CreateClusterWithBodyWithResponse(ctx context.Context, params *CreateClusterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error)

	// CreateClusterWithResponse Create a cluster
	//
	// Creates a new OSAC-backed OpenShift cluster. `control-plane`
	// dispatches this with the resource `id` as a query parameter (its
	// own generated identifier) and a body containing only `spec`
	// (DD-080) — the request body schema is this same `Cluster` resource
	// type (AEP-133-compliant, DD-113), but `spec` is its only field
	// `control-plane` ever actually populates on the wire; every other
	// `Cluster` field is absent from that request and simply unmarshals
	// to its zero value, which this handler ignores. Idempotent on `id`:
	// a retry with the same `id` returns the existing cluster's current
	// state rather than an error (REQ-CREATE-040/DD-100).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
	CreateClusterWithResponse(ctx context.Context, params *CreateClusterParams, body CreateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error)

	// GetClustersHealthWithResponse Cluster Provider Health Check
	//
	// Returns the health status of the service provider's `cluster`
	// registration, reflecting real OSAC gRPC connectivity and OIDC token
	// validity. Reports the same status as `/api/v1alpha1/vms/health` —
	// this SP's health is a single, global condition (see DD-010 in the
	// Milestone 1 spec).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1alpha1/clusters/health (the `GetClustersHealth` operationId).
	GetClustersHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetClustersHealthResponse, error)

	// DeleteClusterWithResponse Delete a cluster
	//
	// Deletes a cluster. Returns as soon as OSAC acknowledges the
	// request — does not poll for the cluster to actually disappear
	// (REQ-DELETE-040). A `NotFound` from OSAC (already deleted) is
	// treated as success (`204`), mirroring `control-plane`'s own
	// tolerance for this exact case (REQ-DELETE-020/DD-080) — this
	// endpoint therefore never returns `404`.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /api/v1alpha1/clusters/{clusterId} (the `DeleteCluster` operationId).
	DeleteClusterWithResponse(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error)

	// GetClusterWithResponse Get cluster details
	//
	// Returns the cluster's current status. `kubeconfig` is populated
	// only when the mapped status is exactly `ACTIVE` (REQ-GET-020/030).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1alpha1/clusters/{clusterId} (the `GetCluster` operationId).
	GetClusterWithResponse(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*GetClusterResponse, error)

	// GetVMsHealthWithResponse VM Provider Health Check
	//
	// Returns the health status of the service provider's `vm`
	// registration, reflecting real OSAC gRPC connectivity and OIDC token
	// validity. Reports the same status as
	// `/api/v1alpha1/clusters/health` — this SP's health is a single,
	// global condition (see DD-010 in the Milestone 1 spec).
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1alpha1/vms/health (the `GetVMsHealth` operationId).
	GetVMsHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVMsHealthResponse, error)
}

type ListClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ClusterList
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// ApplicationproblemJSON502 the response for an HTTP 502 `application/problem+json` response
	ApplicationproblemJSON502 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListClustersResponse) GetJSON200() *ClusterList {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListClustersResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r ListClustersResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListClustersResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON502 returns the response for an HTTP 502 `application/problem+json` response
func (r ListClustersResponse) GetApplicationproblemJSON502() *Error {
	return r.ApplicationproblemJSON502
}

// GetBody returns the raw response body bytes
func (r ListClustersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListClustersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Cluster
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// ApplicationproblemJSON502 the response for an HTTP 502 `application/problem+json` response
	ApplicationproblemJSON502 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateClusterResponse) GetJSON201() *Cluster {
	return r.JSON201
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateClusterResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateClusterResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r CreateClusterResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r CreateClusterResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON502 returns the response for an HTTP 502 `application/problem+json` response
func (r CreateClusterResponse) GetApplicationproblemJSON502() *Error {
	return r.ApplicationproblemJSON502
}

// GetBody returns the raw response body bytes
func (r CreateClusterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateClusterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetClustersHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetClustersHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetClustersHealthResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetClustersHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetClustersHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetClustersHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// ApplicationproblemJSON502 the response for an HTTP 502 `application/problem+json` response
	ApplicationproblemJSON502 *Error
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r DeleteClusterResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r DeleteClusterResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r DeleteClusterResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON502 returns the response for an HTTP 502 `application/problem+json` response
func (r DeleteClusterResponse) GetApplicationproblemJSON502() *Error {
	return r.ApplicationproblemJSON502
}

// GetBody returns the raw response body bytes
func (r DeleteClusterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteClusterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Cluster
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
	// ApplicationproblemJSON502 the response for an HTTP 502 `application/problem+json` response
	ApplicationproblemJSON502 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetClusterResponse) GetJSON200() *Cluster {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetClusterResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetClusterResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetClusterResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetClusterResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON502 returns the response for an HTTP 502 `application/problem+json` response
func (r GetClusterResponse) GetApplicationproblemJSON502() *Error {
	return r.ApplicationproblemJSON502
}

// GetBody returns the raw response body bytes
func (r GetClusterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetClusterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetVMsHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetVMsHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetVMsHealthResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetVMsHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetVMsHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVMsHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVMsHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListClustersWithResponse List clusters
//
// Returns a paginated list of clusters owned by this SP (filtered by
// the `dcm.io/managed-by=dcm` ownership label — REQ-LIST-010). Never
// populates `kubeconfig` on any entry (REQ-LIST-030).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1alpha1/clusters (the `ListClusters` operationId).
func (c *ClientWithResponses) ListClustersWithResponse(ctx context.Context, params *ListClustersParams, reqEditors ...RequestEditorFn) (*ListClustersResponse, error) {
	rsp, err := c.ListClusters(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListClustersResponse(rsp)
}

// CreateClusterWithBodyWithResponse Create a cluster
//
// Creates a new OSAC-backed OpenShift cluster. `control-plane`
// dispatches this with the resource `id` as a query parameter (its
// own generated identifier) and a body containing only `spec`
// (DD-080) — the request body schema is this same `Cluster` resource
// type (AEP-133-compliant, DD-113), but `spec` is its only field
// `control-plane` ever actually populates on the wire; every other
// `Cluster` field is absent from that request and simply unmarshals
// to its zero value, which this handler ignores. Idempotent on `id`:
// a retry with the same `id` returns the existing cluster's current
// state rather than an error (REQ-CREATE-040/DD-100).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
func (c *ClientWithResponses) CreateClusterWithBodyWithResponse(ctx context.Context, params *CreateClusterParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error) {
	rsp, err := c.CreateClusterWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateClusterResponse(rsp)
}

// CreateClusterWithResponse Create a cluster
//
// Creates a new OSAC-backed OpenShift cluster. `control-plane`
// dispatches this with the resource `id` as a query parameter (its
// own generated identifier) and a body containing only `spec`
// (DD-080) — the request body schema is this same `Cluster` resource
// type (AEP-133-compliant, DD-113), but `spec` is its only field
// `control-plane` ever actually populates on the wire; every other
// `Cluster` field is absent from that request and simply unmarshals
// to its zero value, which this handler ignores. Idempotent on `id`:
// a retry with the same `id` returns the existing cluster's current
// state rather than an error (REQ-CREATE-040/DD-100).
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/v1alpha1/clusters (the `CreateCluster` operationId).
func (c *ClientWithResponses) CreateClusterWithResponse(ctx context.Context, params *CreateClusterParams, body CreateClusterJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error) {
	rsp, err := c.CreateCluster(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateClusterResponse(rsp)
}

// GetClustersHealthWithResponse Cluster Provider Health Check
//
// Returns the health status of the service provider's `cluster`
// registration, reflecting real OSAC gRPC connectivity and OIDC token
// validity. Reports the same status as `/api/v1alpha1/vms/health` —
// this SP's health is a single, global condition (see DD-010 in the
// Milestone 1 spec).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1alpha1/clusters/health (the `GetClustersHealth` operationId).
func (c *ClientWithResponses) GetClustersHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetClustersHealthResponse, error) {
	rsp, err := c.GetClustersHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersHealthResponse(rsp)
}

// DeleteClusterWithResponse Delete a cluster
//
// Deletes a cluster. Returns as soon as OSAC acknowledges the
// request — does not poll for the cluster to actually disappear
// (REQ-DELETE-040). A `NotFound` from OSAC (already deleted) is
// treated as success (`204`), mirroring `control-plane`'s own
// tolerance for this exact case (REQ-DELETE-020/DD-080) — this
// endpoint therefore never returns `404`.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /api/v1alpha1/clusters/{clusterId} (the `DeleteCluster` operationId).
func (c *ClientWithResponses) DeleteClusterWithResponse(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error) {
	rsp, err := c.DeleteCluster(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteClusterResponse(rsp)
}

// GetClusterWithResponse Get cluster details
//
// Returns the cluster's current status. `kubeconfig` is populated
// only when the mapped status is exactly `ACTIVE` (REQ-GET-020/030).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1alpha1/clusters/{clusterId} (the `GetCluster` operationId).
func (c *ClientWithResponses) GetClusterWithResponse(ctx context.Context, clusterId ClusterIdPath, reqEditors ...RequestEditorFn) (*GetClusterResponse, error) {
	rsp, err := c.GetCluster(ctx, clusterId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClusterResponse(rsp)
}

// GetVMsHealthWithResponse VM Provider Health Check
//
// Returns the health status of the service provider's `vm`
// registration, reflecting real OSAC gRPC connectivity and OIDC token
// validity. Reports the same status as
// `/api/v1alpha1/clusters/health` — this SP's health is a single,
// global condition (see DD-010 in the Milestone 1 spec).
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1alpha1/vms/health (the `GetVMsHealth` operationId).
func (c *ClientWithResponses) GetVMsHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVMsHealthResponse, error) {
	rsp, err := c.GetVMsHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVMsHealthResponse(rsp)
}

// ParseListClustersResponse parses an HTTP response from a ListClustersWithResponse call
func ParseListClustersResponse(rsp *http.Response) (*ListClustersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListClustersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClusterList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON502 = &dest

	}

	return response, nil
}

// ParseCreateClusterResponse parses an HTTP response from a CreateClusterWithResponse call
func ParseCreateClusterResponse(rsp *http.Response) (*CreateClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Cluster
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON502 = &dest

	}

	return response, nil
}

// ParseGetClustersHealthResponse parses an HTTP response from a GetClustersHealthWithResponse call
func ParseGetClustersHealthResponse(rsp *http.Response) (*GetClustersHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClustersHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseDeleteClusterResponse parses an HTTP response from a DeleteClusterWithResponse call
func ParseDeleteClusterResponse(rsp *http.Response) (*DeleteClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON502 = &dest

	}

	return response, nil
}

// ParseGetClusterResponse parses an HTTP response from a GetClusterWithResponse call
func ParseGetClusterResponse(rsp *http.Response) (*GetClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Cluster
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON502 = &dest

	}

	return response, nil
}

// ParseGetVMsHealthResponse parses an HTTP response from a GetVMsHealthWithResponse call
func ParseGetVMsHealthResponse(rsp *http.Response) (*GetVMsHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVMsHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
